<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Linear Regression | An Introduction to Statistical Learning</title>
  <meta name="description" content="3 Linear Regression | An Introduction to Statistical Learning" />
  <meta name="generator" content="bookdown 0.40.1 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Linear Regression | An Introduction to Statistical Learning" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Linear Regression | An Introduction to Statistical Learning" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="statistical-learning.html"/>
<link rel="next" href="classification.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="islrv2.css" type="text/css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/aaaakshat/cm-web-fonts@latest/fonts.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">ISLRv2 Solutions</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="statistical-learning.html"><a href="statistical-learning.html"><i class="fa fa-check"></i><b>2</b> Statistical Learning</a>
<ul>
<li class="chapter" data-level="2.1" data-path="statistical-learning.html"><a href="statistical-learning.html#conceptual"><i class="fa fa-check"></i><b>2.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="statistical-learning.html"><a href="statistical-learning.html#question-1"><i class="fa fa-check"></i><b>2.1.1</b> Question 1</a></li>
<li class="chapter" data-level="2.1.2" data-path="statistical-learning.html"><a href="statistical-learning.html#question-2"><i class="fa fa-check"></i><b>2.1.2</b> Question 2</a></li>
<li class="chapter" data-level="2.1.3" data-path="statistical-learning.html"><a href="statistical-learning.html#question-3"><i class="fa fa-check"></i><b>2.1.3</b> Question 3</a></li>
<li class="chapter" data-level="2.1.4" data-path="statistical-learning.html"><a href="statistical-learning.html#question-4"><i class="fa fa-check"></i><b>2.1.4</b> Question 4</a></li>
<li class="chapter" data-level="2.1.5" data-path="statistical-learning.html"><a href="statistical-learning.html#question-5"><i class="fa fa-check"></i><b>2.1.5</b> Question 5</a></li>
<li class="chapter" data-level="2.1.6" data-path="statistical-learning.html"><a href="statistical-learning.html#question-6"><i class="fa fa-check"></i><b>2.1.6</b> Question 6</a></li>
<li class="chapter" data-level="2.1.7" data-path="statistical-learning.html"><a href="statistical-learning.html#question-7"><i class="fa fa-check"></i><b>2.1.7</b> Question 7</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="statistical-learning.html"><a href="statistical-learning.html#applied"><i class="fa fa-check"></i><b>2.2</b> Applied</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="statistical-learning.html"><a href="statistical-learning.html#question-8"><i class="fa fa-check"></i><b>2.2.1</b> Question 8</a></li>
<li class="chapter" data-level="2.2.2" data-path="statistical-learning.html"><a href="statistical-learning.html#question-9"><i class="fa fa-check"></i><b>2.2.2</b> Question 9</a></li>
<li class="chapter" data-level="2.2.3" data-path="statistical-learning.html"><a href="statistical-learning.html#question-10"><i class="fa fa-check"></i><b>2.2.3</b> Question 10</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>3</b> Linear Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="linear-regression.html"><a href="linear-regression.html#conceptual-1"><i class="fa fa-check"></i><b>3.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="linear-regression.html"><a href="linear-regression.html#question-1-1"><i class="fa fa-check"></i><b>3.1.1</b> Question 1</a></li>
<li class="chapter" data-level="3.1.2" data-path="linear-regression.html"><a href="linear-regression.html#question-2-1"><i class="fa fa-check"></i><b>3.1.2</b> Question 2</a></li>
<li class="chapter" data-level="3.1.3" data-path="linear-regression.html"><a href="linear-regression.html#question-3-1"><i class="fa fa-check"></i><b>3.1.3</b> Question 3</a></li>
<li class="chapter" data-level="3.1.4" data-path="linear-regression.html"><a href="linear-regression.html#question-4-1"><i class="fa fa-check"></i><b>3.1.4</b> Question 4</a></li>
<li class="chapter" data-level="3.1.5" data-path="linear-regression.html"><a href="linear-regression.html#question-5-1"><i class="fa fa-check"></i><b>3.1.5</b> Question 5</a></li>
<li class="chapter" data-level="3.1.6" data-path="linear-regression.html"><a href="linear-regression.html#question-6-1"><i class="fa fa-check"></i><b>3.1.6</b> Question 6</a></li>
<li class="chapter" data-level="3.1.7" data-path="linear-regression.html"><a href="linear-regression.html#question-7-1"><i class="fa fa-check"></i><b>3.1.7</b> Question 7</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="linear-regression.html"><a href="linear-regression.html#applied-1"><i class="fa fa-check"></i><b>3.2</b> Applied</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="linear-regression.html"><a href="linear-regression.html#question-8-1"><i class="fa fa-check"></i><b>3.2.1</b> Question 8</a></li>
<li class="chapter" data-level="3.2.2" data-path="linear-regression.html"><a href="linear-regression.html#question-9-1"><i class="fa fa-check"></i><b>3.2.2</b> Question 9</a></li>
<li class="chapter" data-level="3.2.3" data-path="linear-regression.html"><a href="linear-regression.html#question-10-1"><i class="fa fa-check"></i><b>3.2.3</b> Question 10</a></li>
<li class="chapter" data-level="3.2.4" data-path="linear-regression.html"><a href="linear-regression.html#question-11"><i class="fa fa-check"></i><b>3.2.4</b> Question 11</a></li>
<li class="chapter" data-level="3.2.5" data-path="linear-regression.html"><a href="linear-regression.html#question-12"><i class="fa fa-check"></i><b>3.2.5</b> Question 12</a></li>
<li class="chapter" data-level="3.2.6" data-path="linear-regression.html"><a href="linear-regression.html#question-13"><i class="fa fa-check"></i><b>3.2.6</b> Question 13</a></li>
<li class="chapter" data-level="3.2.7" data-path="linear-regression.html"><a href="linear-regression.html#question-14"><i class="fa fa-check"></i><b>3.2.7</b> Question 14</a></li>
<li class="chapter" data-level="3.2.8" data-path="linear-regression.html"><a href="linear-regression.html#question-15"><i class="fa fa-check"></i><b>3.2.8</b> Question 15</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>4</b> Classification</a>
<ul>
<li class="chapter" data-level="4.1" data-path="classification.html"><a href="classification.html#conceptual-2"><i class="fa fa-check"></i><b>4.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="classification.html"><a href="classification.html#question-1-2"><i class="fa fa-check"></i><b>4.1.1</b> Question 1</a></li>
<li class="chapter" data-level="4.1.2" data-path="classification.html"><a href="classification.html#question-2-2"><i class="fa fa-check"></i><b>4.1.2</b> Question 2</a></li>
<li class="chapter" data-level="4.1.3" data-path="classification.html"><a href="classification.html#question-3-2"><i class="fa fa-check"></i><b>4.1.3</b> Question 3</a></li>
<li class="chapter" data-level="4.1.4" data-path="classification.html"><a href="classification.html#question-4-2"><i class="fa fa-check"></i><b>4.1.4</b> Question 4</a></li>
<li class="chapter" data-level="4.1.5" data-path="classification.html"><a href="classification.html#question-5-2"><i class="fa fa-check"></i><b>4.1.5</b> Question 5</a></li>
<li class="chapter" data-level="4.1.6" data-path="classification.html"><a href="classification.html#question-6-2"><i class="fa fa-check"></i><b>4.1.6</b> Question 6</a></li>
<li class="chapter" data-level="4.1.7" data-path="classification.html"><a href="classification.html#question-7-2"><i class="fa fa-check"></i><b>4.1.7</b> Question 7</a></li>
<li class="chapter" data-level="4.1.8" data-path="classification.html"><a href="classification.html#question-8-2"><i class="fa fa-check"></i><b>4.1.8</b> Question 8</a></li>
<li class="chapter" data-level="4.1.9" data-path="classification.html"><a href="classification.html#question-9-2"><i class="fa fa-check"></i><b>4.1.9</b> Question 9</a></li>
<li class="chapter" data-level="4.1.10" data-path="classification.html"><a href="classification.html#question-10-2"><i class="fa fa-check"></i><b>4.1.10</b> Question 10</a></li>
<li class="chapter" data-level="4.1.11" data-path="classification.html"><a href="classification.html#question-11-1"><i class="fa fa-check"></i><b>4.1.11</b> Question 11</a></li>
<li class="chapter" data-level="4.1.12" data-path="classification.html"><a href="classification.html#question-12-1"><i class="fa fa-check"></i><b>4.1.12</b> Question 12</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="classification.html"><a href="classification.html#applied-2"><i class="fa fa-check"></i><b>4.2</b> Applied</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="classification.html"><a href="classification.html#question-13-1"><i class="fa fa-check"></i><b>4.2.1</b> Question 13</a></li>
<li class="chapter" data-level="4.2.2" data-path="classification.html"><a href="classification.html#question-14-1"><i class="fa fa-check"></i><b>4.2.2</b> Question 14</a></li>
<li class="chapter" data-level="4.2.3" data-path="classification.html"><a href="classification.html#question-15-1"><i class="fa fa-check"></i><b>4.2.3</b> Question 15</a></li>
<li class="chapter" data-level="4.2.4" data-path="classification.html"><a href="classification.html#question-13-2"><i class="fa fa-check"></i><b>4.2.4</b> Question 13</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="resampling-methods.html"><a href="resampling-methods.html"><i class="fa fa-check"></i><b>5</b> Resampling Methods</a>
<ul>
<li class="chapter" data-level="5.1" data-path="resampling-methods.html"><a href="resampling-methods.html#conceptual-3"><i class="fa fa-check"></i><b>5.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="resampling-methods.html"><a href="resampling-methods.html#question-1-3"><i class="fa fa-check"></i><b>5.1.1</b> Question 1</a></li>
<li class="chapter" data-level="5.1.2" data-path="resampling-methods.html"><a href="resampling-methods.html#question-2-3"><i class="fa fa-check"></i><b>5.1.2</b> Question 2</a></li>
<li class="chapter" data-level="5.1.3" data-path="resampling-methods.html"><a href="resampling-methods.html#question-3-3"><i class="fa fa-check"></i><b>5.1.3</b> Question 3</a></li>
<li class="chapter" data-level="5.1.4" data-path="resampling-methods.html"><a href="resampling-methods.html#question-4-3"><i class="fa fa-check"></i><b>5.1.4</b> Question 4</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="resampling-methods.html"><a href="resampling-methods.html#applied-3"><i class="fa fa-check"></i><b>5.2</b> Applied</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="resampling-methods.html"><a href="resampling-methods.html#question-5-3"><i class="fa fa-check"></i><b>5.2.1</b> Question 5</a></li>
<li class="chapter" data-level="5.2.2" data-path="resampling-methods.html"><a href="resampling-methods.html#question-6-3"><i class="fa fa-check"></i><b>5.2.2</b> Question 6</a></li>
<li class="chapter" data-level="5.2.3" data-path="resampling-methods.html"><a href="resampling-methods.html#question-7-3"><i class="fa fa-check"></i><b>5.2.3</b> Question 7</a></li>
<li class="chapter" data-level="5.2.4" data-path="resampling-methods.html"><a href="resampling-methods.html#question-8-3"><i class="fa fa-check"></i><b>5.2.4</b> Question 8</a></li>
<li class="chapter" data-level="5.2.5" data-path="resampling-methods.html"><a href="resampling-methods.html#question-9-3"><i class="fa fa-check"></i><b>5.2.5</b> Question 9</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html"><i class="fa fa-check"></i><b>6</b> Linear Model Selection and Regularization</a>
<ul>
<li class="chapter" data-level="6.1" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#conceptual-4"><i class="fa fa-check"></i><b>6.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-1-4"><i class="fa fa-check"></i><b>6.1.1</b> Question 1</a></li>
<li class="chapter" data-level="6.1.2" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-2-4"><i class="fa fa-check"></i><b>6.1.2</b> Question 2</a></li>
<li class="chapter" data-level="6.1.3" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-3-4"><i class="fa fa-check"></i><b>6.1.3</b> Question 3</a></li>
<li class="chapter" data-level="6.1.4" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-4-4"><i class="fa fa-check"></i><b>6.1.4</b> Question 4</a></li>
<li class="chapter" data-level="6.1.5" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-5-4"><i class="fa fa-check"></i><b>6.1.5</b> Question 5</a></li>
<li class="chapter" data-level="6.1.6" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-6-4"><i class="fa fa-check"></i><b>6.1.6</b> Question 6</a></li>
<li class="chapter" data-level="6.1.7" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-7-4"><i class="fa fa-check"></i><b>6.1.7</b> Question 7</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#applied-4"><i class="fa fa-check"></i><b>6.2</b> Applied</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-8-4"><i class="fa fa-check"></i><b>6.2.1</b> Question 8</a></li>
<li class="chapter" data-level="6.2.2" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-9-4"><i class="fa fa-check"></i><b>6.2.2</b> Question 9</a></li>
<li class="chapter" data-level="6.2.3" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-10-3"><i class="fa fa-check"></i><b>6.2.3</b> Question 10</a></li>
<li class="chapter" data-level="6.2.4" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-11-2"><i class="fa fa-check"></i><b>6.2.4</b> Question 11</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html"><i class="fa fa-check"></i><b>7</b> Moving Beyond Linearity</a>
<ul>
<li class="chapter" data-level="7.1" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#conceptual-5"><i class="fa fa-check"></i><b>7.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-1-5"><i class="fa fa-check"></i><b>7.1.1</b> Question 1</a></li>
<li class="chapter" data-level="7.1.2" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-2-5"><i class="fa fa-check"></i><b>7.1.2</b> Question 2</a></li>
<li class="chapter" data-level="7.1.3" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-3-5"><i class="fa fa-check"></i><b>7.1.3</b> Question 3</a></li>
<li class="chapter" data-level="7.1.4" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-4-5"><i class="fa fa-check"></i><b>7.1.4</b> Question 4</a></li>
<li class="chapter" data-level="7.1.5" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-5-5"><i class="fa fa-check"></i><b>7.1.5</b> Question 5</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#applied-5"><i class="fa fa-check"></i><b>7.2</b> Applied</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-6-5"><i class="fa fa-check"></i><b>7.2.1</b> Question 6</a></li>
<li class="chapter" data-level="7.2.2" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-7-5"><i class="fa fa-check"></i><b>7.2.2</b> Question 7</a></li>
<li class="chapter" data-level="7.2.3" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-8-5"><i class="fa fa-check"></i><b>7.2.3</b> Question 8</a></li>
<li class="chapter" data-level="7.2.4" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-9-5"><i class="fa fa-check"></i><b>7.2.4</b> Question 9</a></li>
<li class="chapter" data-level="7.2.5" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-10-4"><i class="fa fa-check"></i><b>7.2.5</b> Question 10</a></li>
<li class="chapter" data-level="7.2.6" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-11-3"><i class="fa fa-check"></i><b>7.2.6</b> Question 11</a></li>
<li class="chapter" data-level="7.2.7" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-12-2"><i class="fa fa-check"></i><b>7.2.7</b> Question 12</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tree-based-methods.html"><a href="tree-based-methods.html"><i class="fa fa-check"></i><b>8</b> Tree-Based Methods</a>
<ul>
<li class="chapter" data-level="8.1" data-path="tree-based-methods.html"><a href="tree-based-methods.html#conceptual-6"><i class="fa fa-check"></i><b>8.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-1-6"><i class="fa fa-check"></i><b>8.1.1</b> Question 1</a></li>
<li class="chapter" data-level="8.1.2" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-2-6"><i class="fa fa-check"></i><b>8.1.2</b> Question 2</a></li>
<li class="chapter" data-level="8.1.3" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-3-6"><i class="fa fa-check"></i><b>8.1.3</b> Question 3</a></li>
<li class="chapter" data-level="8.1.4" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-4-6"><i class="fa fa-check"></i><b>8.1.4</b> Question 4</a></li>
<li class="chapter" data-level="8.1.5" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-5-6"><i class="fa fa-check"></i><b>8.1.5</b> Question 5</a></li>
<li class="chapter" data-level="8.1.6" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-6-6"><i class="fa fa-check"></i><b>8.1.6</b> Question 6</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="tree-based-methods.html"><a href="tree-based-methods.html#applied-6"><i class="fa fa-check"></i><b>8.2</b> Applied</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-7-6"><i class="fa fa-check"></i><b>8.2.1</b> Question 7</a></li>
<li class="chapter" data-level="8.2.2" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-8-6"><i class="fa fa-check"></i><b>8.2.2</b> Question 8</a></li>
<li class="chapter" data-level="8.2.3" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-9-6"><i class="fa fa-check"></i><b>8.2.3</b> Question 9</a></li>
<li class="chapter" data-level="8.2.4" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-10-5"><i class="fa fa-check"></i><b>8.2.4</b> Question 10</a></li>
<li class="chapter" data-level="8.2.5" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-11-4"><i class="fa fa-check"></i><b>8.2.5</b> Question 11</a></li>
<li class="chapter" data-level="8.2.6" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-12-3"><i class="fa fa-check"></i><b>8.2.6</b> Question 12</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="support-vector-machines.html"><a href="support-vector-machines.html"><i class="fa fa-check"></i><b>9</b> Support Vector Machines</a>
<ul>
<li class="chapter" data-level="9.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#conceptual-7"><i class="fa fa-check"></i><b>9.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-1-7"><i class="fa fa-check"></i><b>9.1.1</b> Question 1</a></li>
<li class="chapter" data-level="9.1.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-2-7"><i class="fa fa-check"></i><b>9.1.2</b> Question 2</a></li>
<li class="chapter" data-level="9.1.3" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-3-7"><i class="fa fa-check"></i><b>9.1.3</b> Question 3</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#applied-7"><i class="fa fa-check"></i><b>9.2</b> Applied</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-4-7"><i class="fa fa-check"></i><b>9.2.1</b> Question 4</a></li>
<li class="chapter" data-level="9.2.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-5-7"><i class="fa fa-check"></i><b>9.2.2</b> Question 5</a></li>
<li class="chapter" data-level="9.2.3" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-6-7"><i class="fa fa-check"></i><b>9.2.3</b> Question 6</a></li>
<li class="chapter" data-level="9.2.4" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-7-7"><i class="fa fa-check"></i><b>9.2.4</b> Question 7</a></li>
<li class="chapter" data-level="9.2.5" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-8-7"><i class="fa fa-check"></i><b>9.2.5</b> Question 8</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="deep-learning.html"><a href="deep-learning.html"><i class="fa fa-check"></i><b>10</b> Deep Learning</a>
<ul>
<li class="chapter" data-level="10.1" data-path="deep-learning.html"><a href="deep-learning.html#conceptual-8"><i class="fa fa-check"></i><b>10.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="deep-learning.html"><a href="deep-learning.html#question-1-8"><i class="fa fa-check"></i><b>10.1.1</b> Question 1</a></li>
<li class="chapter" data-level="10.1.2" data-path="deep-learning.html"><a href="deep-learning.html#question-2-8"><i class="fa fa-check"></i><b>10.1.2</b> Question 2</a></li>
<li class="chapter" data-level="10.1.3" data-path="deep-learning.html"><a href="deep-learning.html#question-3-8"><i class="fa fa-check"></i><b>10.1.3</b> Question 3</a></li>
<li class="chapter" data-level="10.1.4" data-path="deep-learning.html"><a href="deep-learning.html#question-4-8"><i class="fa fa-check"></i><b>10.1.4</b> Question 4</a></li>
<li class="chapter" data-level="10.1.5" data-path="deep-learning.html"><a href="deep-learning.html#question-5-8"><i class="fa fa-check"></i><b>10.1.5</b> Question 5</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="deep-learning.html"><a href="deep-learning.html#applied-8"><i class="fa fa-check"></i><b>10.2</b> Applied</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="deep-learning.html"><a href="deep-learning.html#question-6-8"><i class="fa fa-check"></i><b>10.2.1</b> Question 6</a></li>
<li class="chapter" data-level="10.2.2" data-path="deep-learning.html"><a href="deep-learning.html#question-7-8"><i class="fa fa-check"></i><b>10.2.2</b> Question 7</a></li>
<li class="chapter" data-level="10.2.3" data-path="deep-learning.html"><a href="deep-learning.html#question-8-8"><i class="fa fa-check"></i><b>10.2.3</b> Question 8</a></li>
<li class="chapter" data-level="10.2.4" data-path="deep-learning.html"><a href="deep-learning.html#question-9-7"><i class="fa fa-check"></i><b>10.2.4</b> Question 9</a></li>
<li class="chapter" data-level="10.2.5" data-path="deep-learning.html"><a href="deep-learning.html#question-10-6"><i class="fa fa-check"></i><b>10.2.5</b> Question 10</a></li>
<li class="chapter" data-level="10.2.6" data-path="deep-learning.html"><a href="deep-learning.html#question-11-5"><i class="fa fa-check"></i><b>10.2.6</b> Question 11</a></li>
<li class="chapter" data-level="10.2.7" data-path="deep-learning.html"><a href="deep-learning.html#question-12-4"><i class="fa fa-check"></i><b>10.2.7</b> Question 12</a></li>
<li class="chapter" data-level="10.2.8" data-path="deep-learning.html"><a href="deep-learning.html#question-13-3"><i class="fa fa-check"></i><b>10.2.8</b> Question 13</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html"><i class="fa fa-check"></i><b>11</b> Survival Analysis and Censored Data</a>
<ul>
<li class="chapter" data-level="11.1" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#conceptual-9"><i class="fa fa-check"></i><b>11.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-1-9"><i class="fa fa-check"></i><b>11.1.1</b> Question 1</a></li>
<li class="chapter" data-level="11.1.2" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-2-9"><i class="fa fa-check"></i><b>11.1.2</b> Question 2</a></li>
<li class="chapter" data-level="11.1.3" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-3-9"><i class="fa fa-check"></i><b>11.1.3</b> Question 3</a></li>
<li class="chapter" data-level="11.1.4" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-4-9"><i class="fa fa-check"></i><b>11.1.4</b> Question 4</a></li>
<li class="chapter" data-level="11.1.5" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-5-9"><i class="fa fa-check"></i><b>11.1.5</b> Question 5</a></li>
<li class="chapter" data-level="11.1.6" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-6-9"><i class="fa fa-check"></i><b>11.1.6</b> Question 6</a></li>
<li class="chapter" data-level="11.1.7" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-7-9"><i class="fa fa-check"></i><b>11.1.7</b> Question 7</a></li>
<li class="chapter" data-level="11.1.8" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-8-9"><i class="fa fa-check"></i><b>11.1.8</b> Question 8</a></li>
<li class="chapter" data-level="11.1.9" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-9-8"><i class="fa fa-check"></i><b>11.1.9</b> Question 9</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#applied-9"><i class="fa fa-check"></i><b>11.2</b> Applied</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-10-7"><i class="fa fa-check"></i><b>11.2.1</b> Question 10</a></li>
<li class="chapter" data-level="11.2.2" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-11-6"><i class="fa fa-check"></i><b>11.2.2</b> Question 11</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html"><i class="fa fa-check"></i><b>12</b> Unsupervised Learning</a>
<ul>
<li class="chapter" data-level="12.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#conceptual-10"><i class="fa fa-check"></i><b>12.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-1-10"><i class="fa fa-check"></i><b>12.1.1</b> Question 1</a></li>
<li class="chapter" data-level="12.1.2" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-2-10"><i class="fa fa-check"></i><b>12.1.2</b> Question 2</a></li>
<li class="chapter" data-level="12.1.3" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-3-10"><i class="fa fa-check"></i><b>12.1.3</b> Question 3</a></li>
<li class="chapter" data-level="12.1.4" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-4-10"><i class="fa fa-check"></i><b>12.1.4</b> Question 4</a></li>
<li class="chapter" data-level="12.1.5" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-5-10"><i class="fa fa-check"></i><b>12.1.5</b> Question 5</a></li>
<li class="chapter" data-level="12.1.6" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-6-10"><i class="fa fa-check"></i><b>12.1.6</b> Question 6</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#applied-10"><i class="fa fa-check"></i><b>12.2</b> Applied</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-7-10"><i class="fa fa-check"></i><b>12.2.1</b> Question 7</a></li>
<li class="chapter" data-level="12.2.2" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-8-10"><i class="fa fa-check"></i><b>12.2.2</b> Question 8</a></li>
<li class="chapter" data-level="12.2.3" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-9-9"><i class="fa fa-check"></i><b>12.2.3</b> Question 9</a></li>
<li class="chapter" data-level="12.2.4" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-10-8"><i class="fa fa-check"></i><b>12.2.4</b> Question 10</a></li>
<li class="chapter" data-level="12.2.5" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-11-7"><i class="fa fa-check"></i><b>12.2.5</b> Question 11</a></li>
<li class="chapter" data-level="12.2.6" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-12-5"><i class="fa fa-check"></i><b>12.2.6</b> Question 12</a></li>
<li class="chapter" data-level="12.2.7" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-13-4"><i class="fa fa-check"></i><b>12.2.7</b> Question 13</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="multiple-testing.html"><a href="multiple-testing.html"><i class="fa fa-check"></i><b>13</b> Multiple Testing</a>
<ul>
<li class="chapter" data-level="13.1" data-path="multiple-testing.html"><a href="multiple-testing.html#conceptual-11"><i class="fa fa-check"></i><b>13.1</b> Conceptual</a>
<ul>
<li class="chapter" data-level="13.1.1" data-path="multiple-testing.html"><a href="multiple-testing.html#question-1-11"><i class="fa fa-check"></i><b>13.1.1</b> Question 1</a></li>
<li class="chapter" data-level="13.1.2" data-path="multiple-testing.html"><a href="multiple-testing.html#question-2-11"><i class="fa fa-check"></i><b>13.1.2</b> Question 2</a></li>
<li class="chapter" data-level="13.1.3" data-path="multiple-testing.html"><a href="multiple-testing.html#question-3-11"><i class="fa fa-check"></i><b>13.1.3</b> Question 3</a></li>
<li class="chapter" data-level="13.1.4" data-path="multiple-testing.html"><a href="multiple-testing.html#question-4-11"><i class="fa fa-check"></i><b>13.1.4</b> Question 4</a></li>
<li class="chapter" data-level="13.1.5" data-path="multiple-testing.html"><a href="multiple-testing.html#question-5-11"><i class="fa fa-check"></i><b>13.1.5</b> Question 5</a></li>
<li class="chapter" data-level="13.1.6" data-path="multiple-testing.html"><a href="multiple-testing.html#question-6-11"><i class="fa fa-check"></i><b>13.1.6</b> Question 6</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="multiple-testing.html"><a href="multiple-testing.html#applied-11"><i class="fa fa-check"></i><b>13.2</b> Applied</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="multiple-testing.html"><a href="multiple-testing.html#question-7-11"><i class="fa fa-check"></i><b>13.2.1</b> Question 7</a></li>
<li class="chapter" data-level="13.2.2" data-path="multiple-testing.html"><a href="multiple-testing.html#question-8-11"><i class="fa fa-check"></i><b>13.2.2</b> Question 8</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Introduction to Statistical Learning</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-regression" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">3</span> Linear Regression<a href="linear-regression.html#linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="conceptual-1" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Conceptual<a href="linear-regression.html#conceptual-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="question-1-1" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Question 1<a href="linear-regression.html#question-1-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Describe the null hypotheses to which the p-values given in Table 3.4
correspond. Explain what conclusions you can draw based on these p-values.
Your explanation should be phrased in terms of <code>sales</code>, <code>TV</code>, <code>radio</code>, and
<code>newspaper</code>, rather than in terms of the coefficients of the linear model.</p>
</blockquote>
<p>For intercept, that <span class="math inline">\(\beta_0 = 0\)</span>
For the others, that <span class="math inline">\(\beta_n = 0\)</span> (for <span class="math inline">\(n = 1, 2, 3\)</span>)</p>
<p>We can conclude that that without any spending, there are still some sales (the
intercept is not 0). Furthermore, we can conclude that money spent on TV and
radio are significantly associated with increased sales, but the same cannot be
said of newspaper spending.</p>
</div>
<div id="question-2-1" class="section level3 hasAnchor" number="3.1.2">
<h3><span class="header-section-number">3.1.2</span> Question 2<a href="linear-regression.html#question-2-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Carefully explain the differences between the KNN classifier and KNN
regression methods.</p>
</blockquote>
<p>The KNN classifier is categorical and assigns a value based on the most
frequent observed category among <span class="math inline">\(K\)</span> nearest neighbors, whereas KNN regression
assigns a continuous variable, the average of the response variables for
the <span class="math inline">\(K\)</span> nearest neighbors.</p>
</div>
<div id="question-3-1" class="section level3 hasAnchor" number="3.1.3">
<h3><span class="header-section-number">3.1.3</span> Question 3<a href="linear-regression.html#question-3-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Suppose we have a data set with five predictors, <span class="math inline">\(X_1\)</span> = GPA, <span class="math inline">\(X_2\)</span> = IQ,
<span class="math inline">\(X_3\)</span> = Level (1 for College and 0 for High School), <span class="math inline">\(X_4\)</span> = Interaction
between GPA and IQ, and <span class="math inline">\(X_5\)</span> = Interaction between GPA and Level. The
response is starting salary after graduation (in thousands of dollars).
Suppose we use least squares to fit the model, and get <span class="math inline">\(\hat\beta_0 = 50\)</span>,
<span class="math inline">\(\hat\beta_1 = 20\)</span>, <span class="math inline">\(\hat\beta_2 = 0.07\)</span>, <span class="math inline">\(\hat\beta_3 = 35\)</span>, <span class="math inline">\(\hat\beta_4 = 0.01\)</span>, <span class="math inline">\(\hat\beta_5 = -10\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li>Which answer is correct, and why?
<ol style="list-style-type: lower-roman">
<li>For a fixed value of IQ and GPA, high school graduates earn more on
average than college graduates.</li>
<li>For a fixed value of IQ and GPA, college graduates earn more on
average than high school graduates.</li>
<li>For a fixed value of IQ and GPA, high school graduates earn more on
average than college graduates provided that the GPA is high enough.</li>
<li>For a fixed value of IQ and GPA, college graduates earn more on
average than high school graduates provided that the GPA is high
enough.</li>
</ol></li>
</ol>
</blockquote>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="linear-regression.html#cb58-1" aria-hidden="true"></a><span class="kw">library</span>(plotly)</span></code></pre></div>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="linear-regression.html#cb59-1" aria-hidden="true"></a>model &lt;-<span class="st"> </span><span class="cf">function</span>(gpa, iq, level) {</span>
<span id="cb59-2"><a href="linear-regression.html#cb59-2" aria-hidden="true"></a>  <span class="dv">50</span> <span class="op">+</span></span>
<span id="cb59-3"><a href="linear-regression.html#cb59-3" aria-hidden="true"></a><span class="st">  </span>gpa <span class="op">*</span><span class="st"> </span><span class="dv">20</span> <span class="op">+</span></span>
<span id="cb59-4"><a href="linear-regression.html#cb59-4" aria-hidden="true"></a><span class="st">  </span>iq <span class="op">*</span><span class="st"> </span><span class="fl">0.07</span> <span class="op">+</span></span>
<span id="cb59-5"><a href="linear-regression.html#cb59-5" aria-hidden="true"></a><span class="st">  </span>level <span class="op">*</span><span class="st"> </span><span class="dv">35</span> <span class="op">+</span></span>
<span id="cb59-6"><a href="linear-regression.html#cb59-6" aria-hidden="true"></a><span class="st">  </span>gpa <span class="op">*</span><span class="st"> </span>iq <span class="op">*</span><span class="st"> </span><span class="fl">0.01</span> <span class="op">+</span></span>
<span id="cb59-7"><a href="linear-regression.html#cb59-7" aria-hidden="true"></a><span class="st">  </span>gpa <span class="op">*</span><span class="st"> </span>level <span class="op">*</span><span class="st"> </span><span class="dv">-10</span></span>
<span id="cb59-8"><a href="linear-regression.html#cb59-8" aria-hidden="true"></a>}</span>
<span id="cb59-9"><a href="linear-regression.html#cb59-9" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dt">length =</span> <span class="dv">10</span>)</span>
<span id="cb59-10"><a href="linear-regression.html#cb59-10" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">200</span>, <span class="dt">length =</span> <span class="dv">20</span>)</span>
<span id="cb59-11"><a href="linear-regression.html#cb59-11" aria-hidden="true"></a>college &lt;-<span class="st"> </span><span class="kw">t</span>(<span class="kw">outer</span>(x, y, model, <span class="dt">level =</span> <span class="dv">1</span>))</span>
<span id="cb59-12"><a href="linear-regression.html#cb59-12" aria-hidden="true"></a>high_school &lt;-<span class="st"> </span><span class="kw">t</span>(<span class="kw">outer</span>(x, y, model, <span class="dt">level =</span> <span class="dv">0</span>))</span>
<span id="cb59-13"><a href="linear-regression.html#cb59-13" aria-hidden="true"></a></span>
<span id="cb59-14"><a href="linear-regression.html#cb59-14" aria-hidden="true"></a><span class="kw">plot_ly</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y) <span class="op">|</span><span class="er">&gt;</span></span>
<span id="cb59-15"><a href="linear-regression.html#cb59-15" aria-hidden="true"></a><span class="st">  </span><span class="kw">add_surface</span>(</span>
<span id="cb59-16"><a href="linear-regression.html#cb59-16" aria-hidden="true"></a>    <span class="dt">z =</span> <span class="op">~</span>college,</span>
<span id="cb59-17"><a href="linear-regression.html#cb59-17" aria-hidden="true"></a>    <span class="dt">colorscale =</span> <span class="kw">list</span>(<span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="st">&quot;rgb(107,184,214)&quot;</span>, <span class="st">&quot;rgb(0,90,124)&quot;</span>)),</span>
<span id="cb59-18"><a href="linear-regression.html#cb59-18" aria-hidden="true"></a>    <span class="dt">colorbar =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">&quot;College&quot;</span>)) <span class="op">|</span><span class="er">&gt;</span></span>
<span id="cb59-19"><a href="linear-regression.html#cb59-19" aria-hidden="true"></a><span class="st">  </span><span class="kw">add_surface</span>(</span>
<span id="cb59-20"><a href="linear-regression.html#cb59-20" aria-hidden="true"></a>    <span class="dt">z =</span> <span class="op">~</span>high_school,</span>
<span id="cb59-21"><a href="linear-regression.html#cb59-21" aria-hidden="true"></a>    <span class="dt">colorscale =</span> <span class="kw">list</span>(<span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="st">&quot;rgb(255,112,184)&quot;</span>, <span class="st">&quot;rgb(128,0,64)&quot;</span>)),</span>
<span id="cb59-22"><a href="linear-regression.html#cb59-22" aria-hidden="true"></a>    <span class="dt">colorbar =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">&quot;High school&quot;</span>)) <span class="op">|</span><span class="er">&gt;</span></span>
<span id="cb59-23"><a href="linear-regression.html#cb59-23" aria-hidden="true"></a><span class="st">  </span><span class="kw">layout</span>(<span class="dt">scene =</span> <span class="kw">list</span>(</span>
<span id="cb59-24"><a href="linear-regression.html#cb59-24" aria-hidden="true"></a>    <span class="dt">xaxis =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">&quot;GPA&quot;</span>),</span>
<span id="cb59-25"><a href="linear-regression.html#cb59-25" aria-hidden="true"></a>    <span class="dt">yaxis =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">&quot;IQ&quot;</span>),</span>
<span id="cb59-26"><a href="linear-regression.html#cb59-26" aria-hidden="true"></a>    <span class="dt">zaxis =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">&quot;Salary&quot;</span>)))</span></code></pre></div>
<div class="plotly html-widget html-fill-item" id="htmlwidget-1435a62e187ca8a49e70" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-1435a62e187ca8a49e70">{"x":{"visdat":{"1b5bd86f51c":["function () ","plotlyVisDat"]},"cur_data":"1b5bd86f51c","attrs":{"1b5bd86f51c":{"x":[1,1.4444444444444444,1.8888888888888888,2.333333333333333,2.7777777777777777,3.2222222222222223,3.6666666666666665,4.1111111111111107,4.5555555555555554,5],"y":[1,11.473684210526315,21.94736842105263,32.421052631578945,42.89473684210526,53.368421052631575,63.84210526315789,74.315789473684205,84.78947368421052,95.263157894736835,105.73684210526315,116.21052631578947,126.68421052631578,137.15789473684208,147.63157894736841,158.10526315789474,168.57894736842104,179.05263157894734,189.52631578947367,200],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"z":{},"type":"surface","colorscale":[[0,1],["rgb(107,184,214)","rgb(0,90,124)"]],"colorbar":{"title":"College"},"inherit":true},"1b5bd86f51c.1":{"x":[1,1.4444444444444444,1.8888888888888888,2.333333333333333,2.7777777777777777,3.2222222222222223,3.6666666666666665,4.1111111111111107,4.5555555555555554,5],"y":[1,11.473684210526315,21.94736842105263,32.421052631578945,42.89473684210526,53.368421052631575,63.84210526315789,74.315789473684205,84.78947368421052,95.263157894736835,105.73684210526315,116.21052631578947,126.68421052631578,137.15789473684208,147.63157894736841,158.10526315789474,168.57894736842104,179.05263157894734,189.52631578947367,200],"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"z":{},"type":"surface","colorscale":[[0,1],["rgb(255,112,184)","rgb(128,0,64)"]],"colorbar":{"title":"High school"},"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"GPA"},"yaxis":{"title":"IQ"},"zaxis":{"title":"Salary"}},"hovermode":"closest","showlegend":false,"legend":{"yanchor":"top","y":0.33333333333333337}},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"colorbar":{"title":"College","ticklen":2,"len":0.33333333333333331,"lenmode":"fraction","y":1,"yanchor":"top"},"colorscale":[[0,"rgb(107,184,214)"],[1,"rgb(0,90,124)"]],"showscale":true,"x":[1,1.4444444444444444,1.8888888888888888,2.333333333333333,2.7777777777777777,3.2222222222222223,3.6666666666666665,4.1111111111111107,4.5555555555555554,5],"y":[1,11.473684210526315,21.94736842105263,32.421052631578945,42.89473684210526,53.368421052631575,63.84210526315789,74.315789473684205,84.78947368421052,95.263157894736835,105.73684210526315,116.21052631578947,126.68421052631578,137.15789473684208,147.63157894736841,158.10526315789474,168.57894736842104,179.05263157894734,189.52631578947367,200],"z":[[95.079999999999998,99.528888888888886,103.97777777777777,108.42666666666666,112.87555555555554,117.32444444444445,121.77333333333331,126.22222222222223,130.67111111111109,135.12],[95.917894736842101,100.41333333333333,104.90877192982455,109.40421052631579,113.89964912280701,118.39508771929826,122.89052631578946,127.38596491228071,131.88140350877194,136.37684210526317],[96.755789473684217,101.29777777777778,105.83976608187135,110.38175438596492,114.92374269005848,119.46573099415207,124.0077192982456,128.5497076023392,133.09169590643273,137.63368421052633],[97.59368421052632,102.18222222222222,106.77076023391812,111.35929824561403,115.94783625730994,120.53637426900585,125.12491228070175,129.71345029239768,134.30198830409358,138.89052631578949],[98.431578947368422,103.06666666666666,107.70175438596492,112.33684210526313,116.97192982456141,121.60701754385966,126.2421052631579,130.87719298245614,135.51228070175438,140.14736842105262],[99.269473684210524,103.9511111111111,108.63274853801168,113.31438596491226,117.99602339181288,122.67766081871343,127.35929824561404,132.04093567251462,136.72257309941523,141.40421052631578],[100.10736842105264,104.83555555555556,109.56374269005849,114.29192982456139,119.02011695906435,123.74830409356724,128.47649122807019,133.20467836257311,137.93286549707602,142.66105263157894],[100.94526315789473,105.72,110.49473684210525,115.26947368421052,120.04421052631579,124.81894736842105,129.59368421052631,134.36842105263159,139.14315789473687,143.9178947368421],[101.78315789473685,106.60444444444444,111.42573099415202,116.24701754385966,121.06830409356726,125.88959064327486,130.71087719298245,135.53216374269005,140.35345029239767,145.17473684210526],[102.62105263157893,107.48888888888888,112.35672514619881,117.22456140350876,122.09239766081873,126.96023391812867,131.8280701754386,136.69590643274853,141.56374269005846,146.43157894736842],[103.45894736842105,108.37333333333333,113.28771929824561,118.20210526315789,123.11649122807017,128.03087719298247,132.94526315789471,137.85964912280701,142.77403508771931,147.68842105263158],[104.29684210526317,109.25777777777778,114.2187134502924,119.17964912280702,124.14058479532164,129.10152046783628,134.06245614035086,139.0233918128655,143.98432748538011,148.94526315789474],[105.13473684210526,110.14222222222222,115.14970760233919,120.15719298245612,125.16467836257311,130.17216374269006,135.17964912280701,140.18713450292398,145.19461988304096,150.2021052631579],[105.97263157894737,111.02666666666667,116.08070175438598,121.13473684210526,126.18877192982458,131.24280701754387,136.29684210526315,141.35087719298244,146.40491228070175,151.45894736842104],[106.81052631578947,111.91111111111111,117.01169590643275,122.11228070175439,127.21286549707605,132.31345029239765,137.41403508771933,142.51461988304092,147.61520467836255,152.7157894736842],[107.64842105263158,112.79555555555555,117.94269005847954,123.08982456140352,128.23695906432752,133.38409356725145,138.53122807017544,143.67836257309943,148.8254970760234,153.97263157894739],[108.48631578947368,113.67999999999999,118.87368421052631,124.06736842105265,129.26105263157896,134.45473684210526,139.64842105263159,144.84210526315792,150.03578947368425,155.22947368421055],[109.3242105263158,114.56444444444445,119.80467836257307,125.04491228070175,130.28514619883043,135.52538011695907,140.76561403508774,146.00584795321637,151.24608187134504,156.48631578947368],[110.16210526315788,115.44888888888887,120.73567251461986,126.02245614035085,131.30923976608187,136.59602339181288,141.88280701754388,147.16959064327486,152.45637426900583,157.74315789473684],[111,116.33333333333333,121.66666666666666,126.99999999999999,132.33333333333331,137.66666666666669,143.00000000000003,148.33333333333334,153.66666666666669,159]],"type":"surface","frame":null},{"colorbar":{"title":"High school","ticklen":2,"len":0.33333333333333331,"lenmode":"fraction","y":0.66666666666666674,"yanchor":"top"},"colorscale":[[0,"rgb(255,112,184)"],[1,"rgb(128,0,64)"]],"showscale":true,"x":[1,1.4444444444444444,1.8888888888888888,2.333333333333333,2.7777777777777777,3.2222222222222223,3.6666666666666665,4.1111111111111107,4.5555555555555554,5],"y":[1,11.473684210526315,21.94736842105263,32.421052631578945,42.89473684210526,53.368421052631575,63.84210526315789,74.315789473684205,84.78947368421052,95.263157894736835,105.73684210526315,116.21052631578947,126.68421052631578,137.15789473684208,147.63157894736841,158.10526315789474,168.57894736842104,179.05263157894734,189.52631578947367,200],"z":[[70.079999999999998,78.973333333333329,87.86666666666666,96.759999999999977,105.65333333333332,114.54666666666665,123.43999999999998,132.33333333333334,141.22666666666666,150.12],[70.917894736842101,79.85777777777777,88.797660818713439,97.737543859649108,106.67742690058479,115.61730994152046,124.55719298245613,133.49707602339183,142.43695906432748,151.37684210526317],[71.755789473684217,80.742222222222225,89.728654970760232,98.715087719298239,107.70152046783626,116.68795321637427,125.67438596491228,134.66081871345031,143.6472514619883,152.63368421052633],[72.59368421052632,81.626666666666665,90.659649122807011,99.692631578947356,108.72561403508772,117.75859649122806,126.79157894736841,135.8245614035088,144.85754385964913,153.89052631578949],[73.431578947368422,82.511111111111106,91.590643274853804,100.67017543859649,109.74970760233919,118.82923976608187,127.90877192982457,136.98830409356725,146.06783625730992,155.14736842105262],[74.269473684210524,83.395555555555546,92.521637426900568,101.6477192982456,110.77380116959064,119.89988304093566,129.0259649122807,138.15204678362574,147.27812865497077,156.40421052631578],[75.107368421052641,84.280000000000001,93.452631578947361,102.62526315789474,111.79789473684211,120.97052631578947,130.14315789473685,139.31578947368422,148.48842105263159,157.66105263157894],[75.945263157894729,85.164444444444442,94.38362573099414,103.60280701754384,112.82198830409357,122.04116959064326,131.26035087719296,140.4795321637427,149.69871345029242,158.9178947368421],[76.783157894736846,86.048888888888882,95.314619883040933,104.58035087719297,113.84608187134504,123.11181286549707,132.37754385964911,141.64327485380116,150.90900584795321,160.17473684210526],[77.621052631578934,86.933333333333323,96.245614035087712,105.55789473684209,114.8701754385965,124.18245614035088,133.49473684210525,142.80701754385964,152.11929824561403,161.43157894736842],[78.45894736842105,87.817777777777778,97.176608187134491,106.53543859649122,115.89426900584796,125.25309941520467,134.61192982456137,143.97076023391813,153.32959064327486,162.68842105263158],[79.296842105263167,88.702222222222218,98.107602339181284,107.51298245614035,116.91836257309943,126.32374269005848,135.72912280701752,145.13450292397661,154.53988304093568,163.94526315789474],[80.134736842105255,89.586666666666659,99.038596491228063,108.49052631578947,117.94245614035087,127.39438596491227,136.84631578947366,146.2982456140351,155.7501754385965,165.2021052631579],[80.972631578947372,90.471111111111114,99.969590643274856,109.46807017543858,118.96654970760234,128.4650292397661,137.96350877192981,147.46198830409355,156.96046783625729,166.45894736842104],[81.810526315789474,91.355555555555554,100.90058479532163,110.4456140350877,119.9906432748538,129.53567251461988,139.08070175438598,148.62573099415204,158.17076023391812,167.7157894736842],[82.648421052631576,92.239999999999995,101.83157894736841,111.42315789473683,121.01473684210526,130.60631578947368,140.1978947368421,149.78947368421055,159.38105263157897,168.97263157894739],[83.486315789473679,93.124444444444435,102.76257309941519,112.40070175438595,122.03883040935672,131.67695906432749,141.31508771929825,150.95321637426903,160.59134502923979,170.22947368421055],[84.324210526315795,94.00888888888889,103.69356725146199,113.37824561403508,123.06292397660819,132.7476023391813,142.43228070175439,152.11695906432749,161.80163742690058,171.48631578947368],[85.162105263157883,94.893333333333317,104.62456140350876,114.3557894736842,124.08701754385966,133.81824561403511,143.54947368421054,153.28070175438597,163.01192982456141,172.74315789473684],[86,95.777777777777771,105.55555555555554,115.33333333333333,125.11111111111111,134.88888888888891,144.66666666666669,154.44444444444446,164.22222222222223,174]],"type":"surface","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Option iii correct.</p>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Predict the salary of a college graduate with IQ of 110 and a GPA of 4.0.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="linear-regression.html#cb60-1" aria-hidden="true"></a><span class="kw">model</span>(<span class="dt">gpa =</span> <span class="dv">4</span>, <span class="dt">iq =</span> <span class="dv">110</span>, <span class="dt">level =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 137.1</code></pre>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>True or false: Since the coefficient for the GPA/IQ interaction term is
very small, there is very little evidence of an interaction effect. Justify
your answer.</li>
</ol>
</blockquote>
<p>This is false. It is important to remember that GPA and IQ vary over different
scales. It is better to explicitly test the significance of the interaction
effect, and/or visualize or quantify the effect on sales under realistic ranges
of GPA/IQ values.</p>
</div>
<div id="question-4-1" class="section level3 hasAnchor" number="3.1.4">
<h3><span class="header-section-number">3.1.4</span> Question 4<a href="linear-regression.html#question-4-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>I collect a set of data (<span class="math inline">\(n = 100\)</span> observations) containing a single predictor
and a quantitative response. I then fit a linear regression model to the data,
as well as a separate cubic regression, i.e. <span class="math inline">\(Y = \beta_0 + \beta_1X + \beta_2X^2 + \beta_3X^3 + \epsilon\)</span>.</p>
<ol style="list-style-type: lower-alpha">
<li>Suppose that the true relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is linear,
i.e. <span class="math inline">\(Y = \beta_0 + \beta_1X + \epsilon\)</span>. Consider the training residual
sum of squares (RSS) for the linear regression, and also the training RSS
for the cubic regression. Would we expect one to be lower than the other,
would we expect them to be the same, or is there not enough information to
tell? Justify your answer.</li>
</ol>
</blockquote>
<p>You would expect the cubic regression to have lower RSS since it is at least
as flexible as the linear regression.</p>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Answer (a) using test rather than training RSS.</li>
</ol>
</blockquote>
<p>Though we could not be certain, the test RSS would likely be higher due to
overfitting.</p>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Suppose that the true relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is not linear, but
we don’t know how far it is from linear. Consider the training RSS for the
linear regression, and also the training RSS for the cubic regression.
Would we expect one to be lower than the other, would we expect them to be
the same, or is there not enough information to tell? Justify your answer.</li>
</ol>
</blockquote>
<p>You would expect the cubic regression to have lower RSS since it is at least
as flexible as the linear regression.</p>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Answer (c) using test rather than training RSS.</li>
</ol>
</blockquote>
<p>There is not enough information to tell, it depends on how non-linear the
true relationship is.</p>
</div>
<div id="question-5-1" class="section level3 hasAnchor" number="3.1.5">
<h3><span class="header-section-number">3.1.5</span> Question 5<a href="linear-regression.html#question-5-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Consider the fitted values that result from performing linear regression
without an intercept. In this setting, the ith fitted value takes the form
<span class="math display">\[\hat{y}_i = x_i\hat\beta,\]</span>
where
<span class="math display">\[\hat{\beta} = \left(\sum_{i=1}^nx_iy_i\right) / \left(\sum_{i&#39; = 1}^n x^2_{i&#39;}\right).\]</span>
show that we can write
<span class="math display">\[\hat{y}_i = \sum_{i&#39; = 1}^na_{i&#39;}y_{i&#39;}\]</span>
What is <span class="math inline">\(a_{i&#39;}\)</span>?</p>
<p><em>Note: We interpret this result by saying that the fitted
values from linear regression are linear combinations of the response values.</em></p>
</blockquote>
<p><span class="math display">\[\begin{align}
\hat{y}_i 
  &amp; = x_i \frac{\sum_{i=1}^nx_iy_i}{\sum_{i&#39; = 1}^n x^2_{i&#39;}} \\
  &amp; = x_i \frac{\sum_{i&#39;=1}^nx_{i&#39;}y_{i&#39;}}{\sum_{i&#39;&#39; = 1}^n x^2_{i&#39;&#39;}} \\
  &amp; = \frac{\sum_{i&#39;=1}^n x_i x_{i&#39;}y_{i&#39;}}{\sum_{i&#39;&#39; = 1}^n x^2_{i&#39;&#39;}} \\
  &amp; = \sum_{i&#39;=1}^n  \frac{ x_i x_{i&#39;}y_{i&#39;}}{\sum_{i&#39;&#39; = 1}^n x^2_{i&#39;&#39;}} \\
  &amp; = \sum_{i&#39;=1}^n  \frac{ x_i x_{i&#39;}}{\sum_{i&#39;&#39; = 1}^n x^2_{i&#39;&#39;}} y_{i&#39;}
\end{align}\]</span></p>
<p>therefore,</p>
<p><span class="math display">\[a_{i&#39;} = \frac{ x_i x_{i&#39;}}{\sum x^2}\]</span></p>
</div>
<div id="question-6-1" class="section level3 hasAnchor" number="3.1.6">
<h3><span class="header-section-number">3.1.6</span> Question 6<a href="linear-regression.html#question-6-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Using (3.4), argue that in the case of simple linear regression, the
least squares line always passes through the point <span class="math inline">\((\bar{x}, \bar{y})\)</span>.</p>
</blockquote>
<p>when <span class="math inline">\(x = \bar{x}\)</span> what is <span class="math inline">\(y\)</span>?</p>
<p><span class="math display">\[\begin{align}
y &amp;= \hat\beta_0 + \hat\beta_1\bar{x} \\
  &amp;= \bar{y} - \hat\beta_1\bar{x} + \hat\beta_1\bar{x} \\
  &amp;= \bar{y}
\end{align}\]</span></p>
</div>
<div id="question-7-1" class="section level3 hasAnchor" number="3.1.7">
<h3><span class="header-section-number">3.1.7</span> Question 7<a href="linear-regression.html#question-7-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>It is claimed in the text that in the case of simple linear regression
of <span class="math inline">\(Y\)</span> onto <span class="math inline">\(X\)</span>, the <span class="math inline">\(R^2\)</span> statistic (3.17) is equal to the square of the
correlation between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> (3.18). Prove that this is the case. For
simplicity, you may assume that <span class="math inline">\(\bar{x} = \bar{y} = 0\)</span>.</p>
</blockquote>
<p>We have the following equations:</p>
<p><span class="math display">\[ R^2 = \frac{\textit{TSS} - \textit{RSS}}{\textit{TSS}} \]</span>
<span class="math display">\[ Cor(x,y) = \frac{\sum_i (x_i-\bar{x})(y_i - \bar{y})}{\sqrt{\sum_i(x_i - \bar{x})^2}\sqrt{\sum_i(y_i - \bar{y})^2}} \]</span></p>
<p>As above, its important to remember <span class="math inline">\(\sum_i x_i = \sum_j x_j\)</span></p>
<p>when <span class="math inline">\(\bar{x} = \bar{y} = 0\)</span>
<span class="math display">\[ Cor(x,y)^2 = \frac{(\sum_ix_iy_i)^2}{\sum_ix_i^2 \sum_iy_i^2} \]</span></p>
<p>Also note that:</p>
<p><span class="math display">\[\hat{y}_i = \hat\beta_o + \hat\beta_1x_i = x_i\frac{\sum_j{x_jy_j}}{\sum_jx_j^2}\]</span></p>
<p>Therefore, given that <span class="math inline">\(RSS = \sum_i(y_i - \hat{y}_i)^2\)</span> and
<span class="math inline">\(\textit{TSS} = \sum_i(y_i - \bar{y})^2 = \sum_iy_i^2\)</span></p>
<p><span class="math display">\[\begin{align}
R^2 &amp;= \frac{\sum_iy_i^2 - \sum_i(y_i - x_i\frac{\sum_j{x_jy_j}}{\sum_jx_j^2})^2}
            {\sum_iy_i^2} \\

    &amp;= \frac{\sum_iy_i^2 - \sum_i(
          y_i^2 -
          2y_ix_i\frac{\sum_j{x_jy_j}}{\sum_jx_j^2} +
          x_i^2 (\frac{\sum_j{x_jy_j}}{\sum_jx_j^2})^2
        )}{\sum_iy_i^2} \\

    &amp;= \frac{
          2\sum_i(y_ix_i\frac{\sum_j{x_jy_j}}{\sum_jx_j^2}) -
          \sum_i(x_i^2 (\frac{\sum_j{x_jy_j}}{\sum_jx_j^2})^2)
        }{\sum_iy_i^2} \\

    &amp;= \frac{
          2\sum_i(y_ix_i) \frac{\sum_j{x_jy_j}}{\sum_jx_j^2} -
          \sum_i(x_i^2) \frac{(\sum_j{x_jy_j})^2}{(\sum_jx_j^2)^2}
        }{\sum_iy_i^2} \\

    &amp;= \frac{
          2\frac{(\sum_i{x_iy_i})^2}{\sum_jx_j^2} -
          \frac{(\sum_i{x_iy_i})^2}{\sum_jx_j^2}
        }{\sum_iy_i^2} \\

    &amp;= \frac{(\sum_i{x_iy_i})^2}{\sum_ix_i^2 \sum_iy_i^2}
\end{align}\]</span></p>
</div>
</div>
<div id="applied-1" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Applied<a href="linear-regression.html#applied-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="question-8-1" class="section level3 hasAnchor" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Question 8<a href="linear-regression.html#question-8-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>This question involves the use of simple linear regression on the Auto
data set.</p>
<ol style="list-style-type: lower-alpha">
<li>Use the <code>lm()</code> function to perform a simple linear regression with <code>mpg</code> as
the response and <code>horsepower</code> as the predictor. Use the <code>summary()</code> function
to print the results. Comment on the output. For example:</li>
<li>Is there a relationship between the predictor and the response?</li>
</ol>
<ol start="2" style="list-style-type: lower-roman">
<li>How strong is the relationship between the predictor and the response?</li>
<li>Is the relationship between the predictor and the response positive or
negative?</li>
<li>What is the predicted mpg associated with a horsepower of 98?</li>
<li>What are the associated 95% confidence and prediction intervals?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="linear-regression.html#cb62-1" aria-hidden="true"></a><span class="kw">library</span>(ISLR2)</span>
<span id="cb62-2"><a href="linear-regression.html#cb62-2" aria-hidden="true"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>horsepower, <span class="dt">data =</span> Auto)</span>
<span id="cb62-3"><a href="linear-regression.html#cb62-3" aria-hidden="true"></a><span class="kw">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ horsepower, data = Auto)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.5710  -3.2592  -0.3435   2.7630  16.9240 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 39.935861   0.717499   55.66   &lt;2e-16 ***
## horsepower  -0.157845   0.006446  -24.49   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.906 on 390 degrees of freedom
## Multiple R-squared:  0.6059, Adjusted R-squared:  0.6049 
## F-statistic: 599.7 on 1 and 390 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Yes, there is a significant relationship between predictor and response. For
every unit increase in horsepower, mpg reduces by 0.16 (a negative
relationship).</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="linear-regression.html#cb64-1" aria-hidden="true"></a><span class="kw">predict</span>(fit, <span class="kw">data.frame</span>(<span class="dt">horsepower =</span> <span class="dv">98</span>), <span class="dt">interval =</span> <span class="st">&quot;confidence&quot;</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 24.46708 23.97308 24.96108</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="linear-regression.html#cb66-1" aria-hidden="true"></a><span class="kw">predict</span>(fit, <span class="kw">data.frame</span>(<span class="dt">horsepower =</span> <span class="dv">98</span>), <span class="dt">interval =</span> <span class="st">&quot;prediction&quot;</span>)</span></code></pre></div>
<pre><code>##        fit     lwr      upr
## 1 24.46708 14.8094 34.12476</code></pre>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Plot the response and the predictor. Use the <code>abline()</code> function to display
the least squares regression line.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="linear-regression.html#cb68-1" aria-hidden="true"></a><span class="kw">plot</span>(Auto<span class="op">$</span>horsepower, Auto<span class="op">$</span>mpg, <span class="dt">xlab =</span> <span class="st">&quot;horsepower&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;mpg&quot;</span>)</span>
<span id="cb68-2"><a href="linear-regression.html#cb68-2" aria-hidden="true"></a><span class="kw">abline</span>(fit)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Use the <code>plot()</code> function to produce diagnostic plots of the least squares
regression fit. Comment on any problems you see with the fit.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="linear-regression.html#cb69-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb69-2"><a href="linear-regression.html#cb69-2" aria-hidden="true"></a><span class="kw">plot</span>(fit, <span class="dt">cex =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>The residuals show a trend with respect to the fitted values suggesting a
non-linear relationship.</p>
</div>
<div id="question-9-1" class="section level3 hasAnchor" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Question 9<a href="linear-regression.html#question-9-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>This question involves the use of multiple linear regression on the <code>Auto</code>
data set.</p>
<ol style="list-style-type: lower-alpha">
<li>Produce a scatterplot matrix which includes all of the variables in the
data set.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="linear-regression.html#cb70-1" aria-hidden="true"></a><span class="kw">pairs</span>(Auto, <span class="dt">cex =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Compute the matrix of correlations between the variables using the function
<code>cor()</code>. You will need to exclude the name variable, <code>name</code> which is
qualitative.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="linear-regression.html#cb71-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">subset</span>(Auto, <span class="dt">select =</span> <span class="op">-</span>name)</span>
<span id="cb71-2"><a href="linear-regression.html#cb71-2" aria-hidden="true"></a><span class="kw">cor</span>(x)</span></code></pre></div>
<pre><code>##                     mpg  cylinders displacement horsepower     weight
## mpg           1.0000000 -0.7776175   -0.8051269 -0.7784268 -0.8322442
## cylinders    -0.7776175  1.0000000    0.9508233  0.8429834  0.8975273
## displacement -0.8051269  0.9508233    1.0000000  0.8972570  0.9329944
## horsepower   -0.7784268  0.8429834    0.8972570  1.0000000  0.8645377
## weight       -0.8322442  0.8975273    0.9329944  0.8645377  1.0000000
## acceleration  0.4233285 -0.5046834   -0.5438005 -0.6891955 -0.4168392
## year          0.5805410 -0.3456474   -0.3698552 -0.4163615 -0.3091199
## origin        0.5652088 -0.5689316   -0.6145351 -0.4551715 -0.5850054
##              acceleration       year     origin
## mpg             0.4233285  0.5805410  0.5652088
## cylinders      -0.5046834 -0.3456474 -0.5689316
## displacement   -0.5438005 -0.3698552 -0.6145351
## horsepower     -0.6891955 -0.4163615 -0.4551715
## weight         -0.4168392 -0.3091199 -0.5850054
## acceleration    1.0000000  0.2903161  0.2127458
## year            0.2903161  1.0000000  0.1815277
## origin          0.2127458  0.1815277  1.0000000</code></pre>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Use the <code>lm()</code> function to perform a multiple linear regression with <code>mpg</code>
as the response and all other variables except name as the predictors. Use
the <code>summary()</code> function to print the results. Comment on the output. For
instance:
<ol style="list-style-type: lower-roman">
<li>Is there a relationship between the predictors and the response?</li>
<li>Which predictors appear to have a statistically significant relationship
to the response?</li>
<li>What does the coefficient for the <code>year</code> variable suggest?</li>
</ol></li>
</ol>
</blockquote>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="linear-regression.html#cb73-1" aria-hidden="true"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> x)</span>
<span id="cb73-2"><a href="linear-regression.html#cb73-2" aria-hidden="true"></a><span class="kw">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ ., data = x)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.5903 -2.1565 -0.1169  1.8690 13.0604 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -17.218435   4.644294  -3.707  0.00024 ***
## cylinders     -0.493376   0.323282  -1.526  0.12780    
## displacement   0.019896   0.007515   2.647  0.00844 ** 
## horsepower    -0.016951   0.013787  -1.230  0.21963    
## weight        -0.006474   0.000652  -9.929  &lt; 2e-16 ***
## acceleration   0.080576   0.098845   0.815  0.41548    
## year           0.750773   0.050973  14.729  &lt; 2e-16 ***
## origin         1.426141   0.278136   5.127 4.67e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.328 on 384 degrees of freedom
## Multiple R-squared:  0.8215, Adjusted R-squared:  0.8182 
## F-statistic: 252.4 on 7 and 384 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Yes, there is a relationship between some predictors and response, notably
“displacement” (positive), “weight” (negative), “year” (positive) and
“origin” (positive).</p>
<p>The coefficient for year (which is positive <span class="math inline">\(~0.75\)</span>) suggests that mpg
increases by about this amount every year on average.</p>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Use the <code>plot()</code> function to produce diagnostic plots of the linear
regression fit. Comment on any problems you see with the fit. Do the
residual plots suggest any unusually large outliers? Does the leverage plot
identify any observations with unusually high leverage?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="linear-regression.html#cb75-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb75-2"><a href="linear-regression.html#cb75-2" aria-hidden="true"></a><span class="kw">plot</span>(fit, <span class="dt">cex =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>One point has high leverage, the residuals also show a trend with fitted values.</p>
<blockquote>
<ol start="5" style="list-style-type: lower-alpha">
<li>Use the <code>*</code> and <code>:</code> symbols to fit linear regression models with
interaction effects. Do any interactions appear to be statistically
significant?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="linear-regression.html#cb76-1" aria-hidden="true"></a><span class="kw">summary</span>(<span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>. <span class="op">+</span><span class="st"> </span>weight<span class="op">:</span>horsepower, <span class="dt">data =</span> x))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ . + weight:horsepower, data = x)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.589 -1.617 -0.184  1.541 12.001 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        2.876e+00  4.511e+00   0.638 0.524147    
## cylinders         -2.955e-02  2.881e-01  -0.103 0.918363    
## displacement       5.950e-03  6.750e-03   0.881 0.378610    
## horsepower        -2.313e-01  2.363e-02  -9.791  &lt; 2e-16 ***
## weight            -1.121e-02  7.285e-04 -15.393  &lt; 2e-16 ***
## acceleration      -9.019e-02  8.855e-02  -1.019 0.309081    
## year               7.695e-01  4.494e-02  17.124  &lt; 2e-16 ***
## origin             8.344e-01  2.513e-01   3.320 0.000986 ***
## horsepower:weight  5.529e-05  5.227e-06  10.577  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.931 on 383 degrees of freedom
## Multiple R-squared:  0.8618, Adjusted R-squared:  0.859 
## F-statistic: 298.6 on 8 and 383 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="linear-regression.html#cb78-1" aria-hidden="true"></a><span class="kw">summary</span>(<span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>. <span class="op">+</span><span class="st"> </span>acceleration<span class="op">:</span>horsepower, <span class="dt">data =</span> x))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ . + acceleration:horsepower, data = x)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.0329 -1.8177 -0.1183  1.7247 12.4870 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             -32.499820   4.923380  -6.601 1.36e-10 ***
## cylinders                 0.083489   0.316913   0.263 0.792350    
## displacement             -0.007649   0.008161  -0.937 0.349244    
## horsepower                0.127188   0.024746   5.140 4.40e-07 ***
## weight                   -0.003976   0.000716  -5.552 5.27e-08 ***
## acceleration              0.983282   0.161513   6.088 2.78e-09 ***
## year                      0.755919   0.048179  15.690  &lt; 2e-16 ***
## origin                    1.035733   0.268962   3.851 0.000138 ***
## horsepower:acceleration  -0.012139   0.001772  -6.851 2.93e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.145 on 383 degrees of freedom
## Multiple R-squared:  0.841,  Adjusted R-squared:  0.8376 
## F-statistic: 253.2 on 8 and 383 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="linear-regression.html#cb80-1" aria-hidden="true"></a><span class="kw">summary</span>(<span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>. <span class="op">+</span><span class="st"> </span>cylinders<span class="op">:</span>weight, <span class="dt">data =</span> x))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ . + cylinders:weight, data = x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.9484  -1.7133  -0.1809   1.4530  12.4137 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       7.3143478  5.0076737   1.461  0.14494    
## cylinders        -5.0347425  0.5795767  -8.687  &lt; 2e-16 ***
## displacement      0.0156444  0.0068409   2.287  0.02275 *  
## horsepower       -0.0314213  0.0126216  -2.489  0.01322 *  
## weight           -0.0150329  0.0011125 -13.513  &lt; 2e-16 ***
## acceleration      0.1006438  0.0897944   1.121  0.26306    
## year              0.7813453  0.0464139  16.834  &lt; 2e-16 ***
## origin            0.8030154  0.2617333   3.068  0.00231 ** 
## cylinders:weight  0.0015058  0.0001657   9.088  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.022 on 383 degrees of freedom
## Multiple R-squared:  0.8531, Adjusted R-squared:  0.8501 
## F-statistic: 278.1 on 8 and 383 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>There are at least three cases where the interactions appear to be highly
significant.</p>
<blockquote>
<ol start="6" style="list-style-type: lower-alpha">
<li>Try a few different transformations of the variables, such as <span class="math inline">\(log(X)\)</span>,
<span class="math inline">\(\sqrt{X}\)</span>, <span class="math inline">\(X^2\)</span>. Comment on your findings.</li>
</ol>
</blockquote>
<p>Here I’ll just consider transformations for <code>horsepower</code>.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="linear-regression.html#cb82-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb82-2"><a href="linear-regression.html#cb82-2" aria-hidden="true"></a><span class="kw">plot</span>(Auto<span class="op">$</span>horsepower, Auto<span class="op">$</span>mpg, <span class="dt">cex =</span> <span class="fl">0.2</span>)</span>
<span id="cb82-3"><a href="linear-regression.html#cb82-3" aria-hidden="true"></a><span class="kw">plot</span>(<span class="kw">log</span>(Auto<span class="op">$</span>horsepower), Auto<span class="op">$</span>mpg, <span class="dt">cex =</span> <span class="fl">0.2</span>)</span>
<span id="cb82-4"><a href="linear-regression.html#cb82-4" aria-hidden="true"></a><span class="kw">plot</span>(<span class="kw">sqrt</span>(Auto<span class="op">$</span>horsepower), Auto<span class="op">$</span>mpg, <span class="dt">cex =</span> <span class="fl">0.2</span>)</span>
<span id="cb82-5"><a href="linear-regression.html#cb82-5" aria-hidden="true"></a><span class="kw">plot</span>(Auto<span class="op">$</span>horsepower <span class="op">^</span><span class="st"> </span><span class="dv">2</span>, Auto<span class="op">$</span>mpg, <span class="dt">cex =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="linear-regression.html#cb83-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">subset</span>(Auto, <span class="dt">select =</span> <span class="op">-</span>name)</span>
<span id="cb83-2"><a href="linear-regression.html#cb83-2" aria-hidden="true"></a>x<span class="op">$</span>horsepower &lt;-<span class="st"> </span><span class="kw">log</span>(x<span class="op">$</span>horsepower)</span>
<span id="cb83-3"><a href="linear-regression.html#cb83-3" aria-hidden="true"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> x)</span>
<span id="cb83-4"><a href="linear-regression.html#cb83-4" aria-hidden="true"></a><span class="kw">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ ., data = x)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -9.3115 -2.0041 -0.1726  1.8393 12.6579 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  27.254005   8.589614   3.173  0.00163 ** 
## cylinders    -0.486206   0.306692  -1.585  0.11372    
## displacement  0.019456   0.006876   2.830  0.00491 ** 
## horsepower   -9.506436   1.539619  -6.175 1.69e-09 ***
## weight       -0.004266   0.000694  -6.148 1.97e-09 ***
## acceleration -0.292088   0.103804  -2.814  0.00515 ** 
## year          0.705329   0.048456  14.556  &lt; 2e-16 ***
## origin        1.482435   0.259347   5.716 2.19e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.18 on 384 degrees of freedom
## Multiple R-squared:  0.837,  Adjusted R-squared:  0.834 
## F-statistic: 281.6 on 7 and 384 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="linear-regression.html#cb85-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb85-2"><a href="linear-regression.html#cb85-2" aria-hidden="true"></a><span class="kw">plot</span>(fit, <span class="dt">cex =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
<p>A log transformation of <code>horsepower</code> appears to give a more linear relationship
with mpg.</p>
</div>
<div id="question-10-1" class="section level3 hasAnchor" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Question 10<a href="linear-regression.html#question-10-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>This question should be answered using the <code>Carseats</code> data set.</p>
<ol style="list-style-type: lower-alpha">
<li>Fit a multiple regression model to predict <code>Sales</code> using <code>Price</code>, <code>Urban</code>,
and <code>US</code>.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="linear-regression.html#cb86-1" aria-hidden="true"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(Sales <span class="op">~</span><span class="st"> </span>Price <span class="op">+</span><span class="st"> </span>Urban <span class="op">+</span><span class="st"> </span>US, <span class="dt">data =</span> Carseats)</span></code></pre></div>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Provide an interpretation of each coefficient in the model. Be
careful—some of the variables in the model are qualitative!</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="linear-regression.html#cb87-1" aria-hidden="true"></a><span class="kw">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Sales ~ Price + Urban + US, data = Carseats)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.9206 -1.6220 -0.0564  1.5786  7.0581 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 13.043469   0.651012  20.036  &lt; 2e-16 ***
## Price       -0.054459   0.005242 -10.389  &lt; 2e-16 ***
## UrbanYes    -0.021916   0.271650  -0.081    0.936    
## USYes        1.200573   0.259042   4.635 4.86e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.472 on 396 degrees of freedom
## Multiple R-squared:  0.2393, Adjusted R-squared:  0.2335 
## F-statistic: 41.52 on 3 and 396 DF,  p-value: &lt; 2.2e-16</code></pre>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Write out the model in equation form, being careful to handle the
qualitative variables properly.</li>
</ol>
</blockquote>
<p><span class="math display">\[
\textit{Sales} = 13 + -0.054 \times \textit{Price} + \begin{cases}
   -0.022,   &amp; \text{if $\textit{Urban}$ is Yes, $\textit{US}$ is No} \\
    1.20,    &amp; \text{if $\textit{Urban}$ is No, $\textit{US}$ is Yes} \\
    1.18,    &amp; \text{if $\textit{Urban}$ and $\textit{US}$ is Yes} \\
    0,       &amp; \text{Otherwise}
\end{cases}
\]</span></p>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>For which of the predictors can you reject the null hypothesis
<span class="math inline">\(H_0 : \beta_j = 0\)</span>?</li>
</ol>
</blockquote>
<p>Price and US (Urban shows no significant difference between “No” and “Yes”)</p>
<blockquote>
<ol start="5" style="list-style-type: lower-alpha">
<li>On the basis of your response to the previous question, fit a smaller model
that only uses the predictors for which there is evidence of association
with the outcome.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="linear-regression.html#cb89-1" aria-hidden="true"></a>fit2 &lt;-<span class="st"> </span><span class="kw">lm</span>(Sales <span class="op">~</span><span class="st"> </span>Price <span class="op">+</span><span class="st"> </span>US, <span class="dt">data =</span> Carseats)</span></code></pre></div>
<blockquote>
<ol start="6" style="list-style-type: lower-alpha">
<li>How well do the models in (a) and (e) fit the data?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="linear-regression.html#cb90-1" aria-hidden="true"></a><span class="kw">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Sales ~ Price + Urban + US, data = Carseats)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.9206 -1.6220 -0.0564  1.5786  7.0581 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 13.043469   0.651012  20.036  &lt; 2e-16 ***
## Price       -0.054459   0.005242 -10.389  &lt; 2e-16 ***
## UrbanYes    -0.021916   0.271650  -0.081    0.936    
## USYes        1.200573   0.259042   4.635 4.86e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.472 on 396 degrees of freedom
## Multiple R-squared:  0.2393, Adjusted R-squared:  0.2335 
## F-statistic: 41.52 on 3 and 396 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="linear-regression.html#cb92-1" aria-hidden="true"></a><span class="kw">summary</span>(fit2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Sales ~ Price + US, data = Carseats)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.9269 -1.6286 -0.0574  1.5766  7.0515 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 13.03079    0.63098  20.652  &lt; 2e-16 ***
## Price       -0.05448    0.00523 -10.416  &lt; 2e-16 ***
## USYes        1.19964    0.25846   4.641 4.71e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.469 on 397 degrees of freedom
## Multiple R-squared:  0.2393, Adjusted R-squared:  0.2354 
## F-statistic: 62.43 on 2 and 397 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="linear-regression.html#cb94-1" aria-hidden="true"></a><span class="kw">anova</span>(fit, fit2)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Sales ~ Price + Urban + US
## Model 2: Sales ~ Price + US
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1    396 2420.8                           
## 2    397 2420.9 -1  -0.03979 0.0065 0.9357</code></pre>
<p>They have similar <span class="math inline">\(R^2\)</span> and the model containing the extra variable “Urban” is
non-significantly better.</p>
<blockquote>
<ol start="7" style="list-style-type: lower-alpha">
<li>Using the model from (e), obtain 95% confidence intervals for the
coefficient(s).</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="linear-regression.html#cb96-1" aria-hidden="true"></a><span class="kw">confint</span>(fit2)</span></code></pre></div>
<pre><code>##                   2.5 %      97.5 %
## (Intercept) 11.79032020 14.27126531
## Price       -0.06475984 -0.04419543
## USYes        0.69151957  1.70776632</code></pre>
<blockquote>
<ol start="8" style="list-style-type: lower-alpha">
<li>Is there evidence of outliers or high leverage observations in the model
from (e)?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="linear-regression.html#cb98-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb98-2"><a href="linear-regression.html#cb98-2" aria-hidden="true"></a><span class="kw">plot</span>(fit2, <span class="dt">cex =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Yes, somewhat.</p>
</div>
<div id="question-11" class="section level3 hasAnchor" number="3.2.4">
<h3><span class="header-section-number">3.2.4</span> Question 11<a href="linear-regression.html#question-11" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>In this problem we will investigate the <em>t</em>-statistic for the null hypothesis
<span class="math inline">\(H_0 : \beta = 0\)</span> in simple linear regression without an intercept. To
begin, we generate a predictor <code>x</code> and a response <code>y</code> as follows.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="linear-regression.html#cb99-1" aria-hidden="true"></a><span class="kw">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb99-2"><a href="linear-regression.html#cb99-2" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb99-3"><a href="linear-regression.html#cb99-3" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span></code></pre></div>
</blockquote>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="linear-regression.html#cb100-1" aria-hidden="true"></a><span class="kw">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb100-2"><a href="linear-regression.html#cb100-2" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb100-3"><a href="linear-regression.html#cb100-3" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span></code></pre></div>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>Perform a simple linear regression of <code>y</code> onto <code>x</code>, <em>without</em> an intercept.
Report the coefficient estimate <span class="math inline">\(\hat{\beta}\)</span>, the standard error of this
coefficient estimate, and the <em>t</em>-statistic and <em>p</em>-value associated with the
null hypothesis <span class="math inline">\(H_0 : \beta = 0\)</span>. Comment on these results. (You can
perform regression without an intercept using the command <code>lm(y~x+0)</code>.)</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="linear-regression.html#cb101-1" aria-hidden="true"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="dv">0</span>)</span>
<span id="cb101-2"><a href="linear-regression.html#cb101-2" aria-hidden="true"></a><span class="kw">coef</span>(<span class="kw">summary</span>(fit))</span></code></pre></div>
<pre><code>##   Estimate Std. Error  t value     Pr(&gt;|t|)
## x 1.993876  0.1064767 18.72593 2.642197e-34</code></pre>
<p>There’s a significant positive relationship between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span>. <span class="math inline">\(y\)</span> values are
predicted to be (a little below) twice the <span class="math inline">\(x\)</span> values.</p>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Now perform a simple linear regression of <code>x</code> onto <code>y</code> without an intercept,
and report the coefficient estimate, its standard error, and the
corresponding <em>t</em>-statistic and <em>p</em>-values associated with the null hypothesis
<span class="math inline">\(H_0 : \beta = 0\)</span>. Comment on these results.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="linear-regression.html#cb103-1" aria-hidden="true"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(x <span class="op">~</span><span class="st"> </span>y <span class="op">+</span><span class="st"> </span><span class="dv">0</span>)</span>
<span id="cb103-2"><a href="linear-regression.html#cb103-2" aria-hidden="true"></a><span class="kw">coef</span>(<span class="kw">summary</span>(fit))</span></code></pre></div>
<pre><code>##    Estimate Std. Error  t value     Pr(&gt;|t|)
## y 0.3911145 0.02088625 18.72593 2.642197e-34</code></pre>
<p>There’s a significant positive relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. <span class="math inline">\(x\)</span> values are
predicted to be (a little below) half the <span class="math inline">\(y\)</span> values.</p>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>What is the relationship between the results obtained in (a) and (b)?</li>
</ol>
</blockquote>
<p>Without error, the coefficients would be the inverse of each other (2 and 1/2).
The t-statistic and p-values are the same.</p>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>For the regression of <span class="math inline">\(Y\)</span> onto <span class="math inline">\(X\)</span> without an intercept, the
<em>t</em>-statistic for <span class="math inline">\(H_0 : \beta = 0\)</span> takes the form
<span class="math inline">\(\hat{\beta}/SE(\hat{\beta})\)</span>, where <span class="math inline">\(\hat{\beta}\)</span> is given by (3.38), and
where
<span class="math display">\[
SE(\hat\beta) = \sqrt{\frac{\sum_{i=1}^n(y_i - x_i\hat\beta)^2}{(n-1)\sum_{i&#39;=1}^nx_{i&#39;}^2}}.
\]</span>
(These formulas are slightly different from those given in Sections 3.1.1 and
3.1.2, since here we are performing regression without an intercept.) Show
algebraically, and confirm numerically in R, that the t-statistic can be
written as
<span class="math display">\[
\frac{(\sqrt{n-1}) \sum_{i-1}^nx_iy_i)}
     {\sqrt{(\sum_{i=1}^nx_i^2)(\sum_{i&#39;=1}^ny_{i&#39;}^2)-(\sum_{i&#39;=1}^nx_{i&#39;}y_{i&#39;})^2}}
\]</span></li>
</ol>
</blockquote>
<p><span class="math display">\[ \beta = \sum_i x_i y_i / \sum_{i&#39;} x_{i&#39;}^2 ,\]</span></p>
<p>therefore</p>
<p><span class="math display">\[\begin{align}
t &amp;= \frac{\sum_i x_i y_i \sqrt{n-1} \sqrt{\sum_ix_i^2}}
          {\sum_i x_i^2 \sqrt{\sum_i(y_i - x_i \beta)^2}} \\

  &amp;= \frac{\sum_i x_i y_i \sqrt{n-1}}
          {\sqrt{\sum_ix_i^2 \sum_i(y_i - x_i \beta)^2}} \\

  &amp;= \frac{\sum_i x_i y_i \sqrt{n-1}}
          {\sqrt{
            \sum_ix_i^2
            \sum_i(y_i^2 - 2 y_i x_i \beta + x_i^2 \beta^2)
           }} \\

  &amp;= \frac{\sum_i x_i y_i \sqrt{n-1}}
          {\sqrt{
            \sum_ix_i^2 \sum_iy_i^2 -
            \beta \sum_ix_i^2 (2 \sum_i y_i x_i -\beta \sum_i x_i^2)
           }} \\

  &amp;= \frac{\sum_i x_i y_i \sqrt{n-1}}
          {\sqrt{
            \sum_ix_i^2 \sum_iy_i^2 -
            \sum_i x_i y_i (2 \sum_i y_i x_i - \sum_i x_i y_i)
           }} \\

  &amp;= \frac{\sum_i x_i y_i \sqrt{n-1}}
          {\sqrt{\sum_ix_i^2 \sum_iy_i^2 - (\sum_i x_i y_i)^2}} \\
\end{align}\]</span></p>
<p>We can show this numerically in R by computing <span class="math inline">\(t\)</span> using the above equation.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="linear-regression.html#cb105-1" aria-hidden="true"></a>n &lt;-<span class="st"> </span><span class="kw">length</span>(x)</span>
<span id="cb105-2"><a href="linear-regression.html#cb105-2" aria-hidden="true"></a><span class="kw">sqrt</span>(n <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span><span class="kw">sum</span>(x <span class="op">*</span><span class="st"> </span>y) <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">sum</span>(x <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) <span class="op">*</span><span class="st"> </span><span class="kw">sum</span>(y <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(x <span class="op">*</span><span class="st"> </span>y) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 18.72593</code></pre>
<blockquote>
<ol start="5" style="list-style-type: lower-alpha">
<li>Using the results from (d), argue that the <em>t</em>-statistic for the
regression of y onto x is the same as the <em>t</em>-statistic for the regression
of <code>x</code> onto <code>y</code>.</li>
</ol>
</blockquote>
<p>Swapping <span class="math inline">\(x_i\)</span> for <span class="math inline">\(y_i\)</span> in the formula for <span class="math inline">\(t\)</span> will give the same result.</p>
<blockquote>
<ol start="6" style="list-style-type: lower-alpha">
<li>In <code>R</code>, show that when regression is performed <em>with</em> an intercept, the
<em>t</em>-statistic for <span class="math inline">\(H_0 : \beta_1 = 0\)</span> is the same for the regression of <code>y</code>
onto <code>x</code> as it is for the regression of <code>x</code> onto <code>y</code>.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="linear-regression.html#cb107-1" aria-hidden="true"></a><span class="kw">coef</span>(<span class="kw">summary</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x)))</span></code></pre></div>
<pre><code>##                Estimate Std. Error    t value     Pr(&gt;|t|)
## (Intercept) -0.03769261 0.09698729 -0.3886346 6.983896e-01
## x            1.99893961 0.10772703 18.5555993 7.723851e-34</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="linear-regression.html#cb109-1" aria-hidden="true"></a><span class="kw">coef</span>(<span class="kw">summary</span>(<span class="kw">lm</span>(x <span class="op">~</span><span class="st"> </span>y)))</span></code></pre></div>
<pre><code>##               Estimate Std. Error    t value     Pr(&gt;|t|)
## (Intercept) 0.03880394 0.04266144  0.9095787 3.652764e-01
## y           0.38942451 0.02098690 18.5555993 7.723851e-34</code></pre>
</div>
<div id="question-12" class="section level3 hasAnchor" number="3.2.5">
<h3><span class="header-section-number">3.2.5</span> Question 12<a href="linear-regression.html#question-12" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>This problem involves simple linear regression without an intercept.</p>
<ol style="list-style-type: lower-alpha">
<li>Recall that the coefficient estimate <span class="math inline">\(\hat{\beta}\)</span> for the linear
regression of <span class="math inline">\(Y\)</span> onto <span class="math inline">\(X\)</span> without an intercept is given by (3.38). Under
what circumstance is the coefficient estimate for the regression of <span class="math inline">\(X\)</span>
onto <span class="math inline">\(Y\)</span> the same as the coefficient estimate for the regression of <span class="math inline">\(Y\)</span>
onto <span class="math inline">\(X\)</span>?</li>
</ol>
</blockquote>
<p><span class="math display">\[ \hat\beta = \sum_i x_iy_i / \sum_{i&#39;} x_{i&#39;}^2 \]</span></p>
<p>The coefficient for the regression of X onto Y swaps the <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> variables:</p>
<p><span class="math display">\[ \hat\beta = \sum_i x_iy_i / \sum_{i&#39;} y_{i&#39;}^2 \]</span></p>
<p>So they are the same when <span class="math inline">\(\sum_{i} x_{i}^2 = \sum_{i} y_{i}^2\)</span></p>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Generate an example in <code>R</code> with <span class="math inline">\(n = 100\)</span> observations in which the
coefficient estimate for the regression of <span class="math inline">\(X\)</span> onto <span class="math inline">\(Y\)</span> is different from
the coefficient estimate for the regression of <span class="math inline">\(Y\)</span> onto <span class="math inline">\(X\)</span>.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="linear-regression.html#cb111-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb111-2"><a href="linear-regression.html#cb111-2" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="fl">0.1</span>)</span>
<span id="cb111-3"><a href="linear-regression.html#cb111-3" aria-hidden="true"></a><span class="kw">c</span>(<span class="kw">sum</span>(x<span class="op">^</span><span class="dv">2</span>), <span class="kw">sum</span>(y<span class="op">^</span><span class="dv">2</span>))</span></code></pre></div>
<pre><code>## [1] 105.9889 429.4924</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="linear-regression.html#cb113-1" aria-hidden="true"></a><span class="kw">c</span>(<span class="kw">coef</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x))[<span class="dv">2</span>], <span class="kw">coef</span>(<span class="kw">lm</span>(x <span class="op">~</span><span class="st"> </span>y))[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>##         x         y 
## 2.0106218 0.4962439</code></pre>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Generate an example in <code>R</code> with <span class="math inline">\(n = 100\)</span> observations in which the
coefficient estimate for the regression of <span class="math inline">\(X\)</span> onto <span class="math inline">\(Y\)</span> is the same as the
coefficient estimate for the regression of <span class="math inline">\(Y\)</span> onto <span class="math inline">\(X\)</span>.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="linear-regression.html#cb115-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb115-2"><a href="linear-regression.html#cb115-2" aria-hidden="true"></a>y &lt;-<span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="fl">0.1</span>)</span>
<span id="cb115-3"><a href="linear-regression.html#cb115-3" aria-hidden="true"></a><span class="kw">c</span>(<span class="kw">sum</span>(x<span class="op">^</span><span class="dv">2</span>), <span class="kw">sum</span>(y<span class="op">^</span><span class="dv">2</span>))</span></code></pre></div>
<pre><code>## [1] 135.5844 134.5153</code></pre>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="linear-regression.html#cb117-1" aria-hidden="true"></a><span class="kw">c</span>(<span class="kw">coef</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x))[<span class="dv">2</span>], <span class="kw">coef</span>(<span class="kw">lm</span>(x <span class="op">~</span><span class="st"> </span>y))[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>##         x         y 
## 0.9925051 1.0006765</code></pre>
</div>
<div id="question-13" class="section level3 hasAnchor" number="3.2.6">
<h3><span class="header-section-number">3.2.6</span> Question 13<a href="linear-regression.html#question-13" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>In this exercise you will create some simulated data and will fit simple
linear regression models to it. Make sure to use <code>set.seed(1)</code> prior to
starting part (a) to ensure consistent results.</p>
</blockquote>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="linear-regression.html#cb119-1" aria-hidden="true"></a><span class="kw">set.seed</span>(<span class="dv">1</span>)</span></code></pre></div>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>Using the <code>rnorm()</code> function, create a vector, <code>x</code>, containing 100
observations drawn from a <span class="math inline">\(N(0, 1)\)</span> distribution. This represents a
feature, <span class="math inline">\(X\)</span>.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="linear-regression.html#cb120-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span></code></pre></div>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Using the <code>rnorm()</code> function, create a vector, <code>eps</code>, containing 100
observations drawn from a <span class="math inline">\(N(0, 0.25)\)</span> distribution—a normal
distribution with mean zero and variance 0.25.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="linear-regression.html#cb121-1" aria-hidden="true"></a>eps &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="kw">sqrt</span>(<span class="fl">0.25</span>))</span></code></pre></div>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Using x and <code>eps</code>, generate a vector y according to the model
<span class="math display">\[Y = -1 + 0.5X + \epsilon\]</span>
What is the length of the vector <code>y</code>? What are the values of
<span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> in this linear model?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="linear-regression.html#cb122-1" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="dv">-1</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.5</span> <span class="op">*</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span>eps</span>
<span id="cb122-2"><a href="linear-regression.html#cb122-2" aria-hidden="true"></a><span class="kw">length</span>(y)</span></code></pre></div>
<pre><code>## [1] 100</code></pre>
<p><span class="math inline">\(\beta_0 = -1\)</span> and <span class="math inline">\(\beta_1 = 0.5\)</span></p>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Create a scatterplot displaying the relationship between <code>x</code> and <code>y</code>.
Comment on what you observe.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="linear-regression.html#cb124-1" aria-hidden="true"></a><span class="kw">plot</span>(x, y)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>There is a linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> (with some error).</p>
<blockquote>
<ol start="5" style="list-style-type: lower-alpha">
<li>Fit a least squares linear model to predict <code>y</code> using <code>x</code>. Comment on the
model obtained. How do <span class="math inline">\(\hat\beta_0\)</span> and <span class="math inline">\(\hat\beta_1\)</span> compare to <span class="math inline">\(\beta_0\)</span>
and <span class="math inline">\(\beta_1\)</span>?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="linear-regression.html#cb125-1" aria-hidden="true"></a>fit &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x)</span>
<span id="cb125-2"><a href="linear-regression.html#cb125-2" aria-hidden="true"></a><span class="kw">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.93842 -0.30688 -0.06975  0.26970  1.17309 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.01885    0.04849 -21.010  &lt; 2e-16 ***
## x            0.49947    0.05386   9.273 4.58e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.4814 on 98 degrees of freedom
## Multiple R-squared:  0.4674, Adjusted R-squared:  0.4619 
## F-statistic: 85.99 on 1 and 98 DF,  p-value: 4.583e-15</code></pre>
<p><span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are close to their population values.</p>
<blockquote>
<ol start="6" style="list-style-type: lower-alpha">
<li>Display the least squares line on the scatterplot obtained in (d). Draw the
population regression line on the plot, in a different color. Use the
<code>legend()</code> command to create an appropriate legend.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="linear-regression.html#cb127-1" aria-hidden="true"></a><span class="kw">plot</span>(x, y)</span>
<span id="cb127-2"><a href="linear-regression.html#cb127-2" aria-hidden="true"></a><span class="kw">abline</span>(fit)</span>
<span id="cb127-3"><a href="linear-regression.html#cb127-3" aria-hidden="true"></a><span class="kw">abline</span>(<span class="op">-</span><span class="dv">1</span>, <span class="fl">0.5</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</span>
<span id="cb127-4"><a href="linear-regression.html#cb127-4" aria-hidden="true"></a><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>,</span>
<span id="cb127-5"><a href="linear-regression.html#cb127-5" aria-hidden="true"></a>  <span class="kw">c</span>(<span class="st">&quot;model fit&quot;</span>, <span class="st">&quot;population regression&quot;</span>),</span>
<span id="cb127-6"><a href="linear-regression.html#cb127-6" aria-hidden="true"></a>  <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>),</span>
<span id="cb127-7"><a href="linear-regression.html#cb127-7" aria-hidden="true"></a>  <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb127-8"><a href="linear-regression.html#cb127-8" aria-hidden="true"></a>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<blockquote>
<ol start="7" style="list-style-type: lower-alpha">
<li>Now fit a polynomial regression model that predicts <code>y</code> using <code>x</code> and <code>x^2</code>.
Is there evidence that the quadratic term improves the model fit? Explain
your answer.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="linear-regression.html#cb128-1" aria-hidden="true"></a>fit2 &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(x, <span class="dv">2</span>))</span>
<span id="cb128-2"><a href="linear-regression.html#cb128-2" aria-hidden="true"></a><span class="kw">anova</span>(fit2, fit)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: y ~ poly(x, 2)
## Model 2: y ~ x
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1     97 22.257                           
## 2     98 22.709 -1  -0.45163 1.9682 0.1638</code></pre>
<p>There is no evidence for an improved fit, since the F-test is non-significant.</p>
<blockquote>
<ol start="8" style="list-style-type: lower-alpha">
<li>Repeat (a)–(f) after modifying the data generation process in such a way
that there is <em>less</em> noise in the data. The model (3.39) should remain the
same. You can do this by decreasing the variance of the normal distribution
used to generate the error term <span class="math inline">\(\epsilon\)</span> in (b). Describe your results.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="linear-regression.html#cb130-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb130-2"><a href="linear-regression.html#cb130-2" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="dv">-1</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.5</span> <span class="op">*</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="kw">sqrt</span>(<span class="fl">0.05</span>))</span>
<span id="cb130-3"><a href="linear-regression.html#cb130-3" aria-hidden="true"></a>fit2 &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x)</span>
<span id="cb130-4"><a href="linear-regression.html#cb130-4" aria-hidden="true"></a><span class="kw">summary</span>(fit2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.61308 -0.12553 -0.00391  0.15199  0.41332 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.98917    0.02216  -44.64   &lt;2e-16 ***
## x            0.52375    0.02152   24.33   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.2215 on 98 degrees of freedom
## Multiple R-squared:  0.858,  Adjusted R-squared:  0.8565 
## F-statistic: 592.1 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="linear-regression.html#cb132-1" aria-hidden="true"></a><span class="kw">plot</span>(x, y)</span>
<span id="cb132-2"><a href="linear-regression.html#cb132-2" aria-hidden="true"></a><span class="kw">abline</span>(fit2)</span>
<span id="cb132-3"><a href="linear-regression.html#cb132-3" aria-hidden="true"></a><span class="kw">abline</span>(<span class="op">-</span><span class="dv">1</span>, <span class="fl">0.5</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</span>
<span id="cb132-4"><a href="linear-regression.html#cb132-4" aria-hidden="true"></a><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>,</span>
<span id="cb132-5"><a href="linear-regression.html#cb132-5" aria-hidden="true"></a>  <span class="kw">c</span>(<span class="st">&quot;model fit&quot;</span>, <span class="st">&quot;population regression&quot;</span>),</span>
<span id="cb132-6"><a href="linear-regression.html#cb132-6" aria-hidden="true"></a>  <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>),</span>
<span id="cb132-7"><a href="linear-regression.html#cb132-7" aria-hidden="true"></a>  <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb132-8"><a href="linear-regression.html#cb132-8" aria-hidden="true"></a>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>The data shows less variability and the <span class="math inline">\(R^2\)</span> is higher.</p>
<blockquote>
<ol style="list-style-type: lower-roman">
<li>Repeat (a)–(f) after modifying the data generation process in such a way
that there is <em>more</em> noise in the data. The model (3.39) should remain the
same. You can do this by increasing the variance of the normal distribution
used to generate the error term <span class="math inline">\(\epsilon\)</span> in (b). Describe your results.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="linear-regression.html#cb133-1" aria-hidden="true"></a>x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb133-2"><a href="linear-regression.html#cb133-2" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="dv">-1</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.5</span> <span class="op">*</span><span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb133-3"><a href="linear-regression.html#cb133-3" aria-hidden="true"></a>fit3 &lt;-<span class="st"> </span><span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x)</span>
<span id="cb133-4"><a href="linear-regression.html#cb133-4" aria-hidden="true"></a><span class="kw">summary</span>(fit3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.51014 -0.60549  0.02065  0.70483  2.08980 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.04745    0.09676 -10.825  &lt; 2e-16 ***
## x            0.42505    0.08310   5.115 1.56e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9671 on 98 degrees of freedom
## Multiple R-squared:  0.2107, Adjusted R-squared:  0.2027 
## F-statistic: 26.16 on 1 and 98 DF,  p-value: 1.56e-06</code></pre>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="linear-regression.html#cb135-1" aria-hidden="true"></a><span class="kw">plot</span>(x, y)</span>
<span id="cb135-2"><a href="linear-regression.html#cb135-2" aria-hidden="true"></a><span class="kw">abline</span>(fit3)</span>
<span id="cb135-3"><a href="linear-regression.html#cb135-3" aria-hidden="true"></a><span class="kw">abline</span>(<span class="op">-</span><span class="dv">1</span>, <span class="fl">0.5</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</span>
<span id="cb135-4"><a href="linear-regression.html#cb135-4" aria-hidden="true"></a><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>,</span>
<span id="cb135-5"><a href="linear-regression.html#cb135-5" aria-hidden="true"></a>  <span class="kw">c</span>(<span class="st">&quot;model fit&quot;</span>, <span class="st">&quot;population regression&quot;</span>),</span>
<span id="cb135-6"><a href="linear-regression.html#cb135-6" aria-hidden="true"></a>  <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;red&quot;</span>),</span>
<span id="cb135-7"><a href="linear-regression.html#cb135-7" aria-hidden="true"></a>  <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb135-8"><a href="linear-regression.html#cb135-8" aria-hidden="true"></a>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>The data shows more variability. The <span class="math inline">\(R^2\)</span> is lower.</p>
<blockquote>
<ol start="10" style="list-style-type: lower-alpha">
<li>What are the confidence intervals for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> based on the
original data set, the noisier data set, and the less noisy data set?
Comment on your results.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="linear-regression.html#cb136-1" aria-hidden="true"></a><span class="kw">confint</span>(fit)</span></code></pre></div>
<pre><code>##                  2.5 %     97.5 %
## (Intercept) -1.1150804 -0.9226122
## x            0.3925794  0.6063602</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="linear-regression.html#cb138-1" aria-hidden="true"></a><span class="kw">confint</span>(fit2)</span></code></pre></div>
<pre><code>##                 2.5 %     97.5 %
## (Intercept) -1.033141 -0.9451916
## x            0.481037  0.5664653</code></pre>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="linear-regression.html#cb140-1" aria-hidden="true"></a><span class="kw">confint</span>(fit3)</span></code></pre></div>
<pre><code>##                  2.5 %     97.5 %
## (Intercept) -1.2394772 -0.8554276
## x            0.2601391  0.5899632</code></pre>
<p>The confidence intervals for the coefficients are smaller when there is less
error.</p>
</div>
<div id="question-14" class="section level3 hasAnchor" number="3.2.7">
<h3><span class="header-section-number">3.2.7</span> Question 14<a href="linear-regression.html#question-14" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>This problem focuses on the collinearity problem.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Perform the following commands in R :</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="linear-regression.html#cb142-1" aria-hidden="true"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb142-2"><a href="linear-regression.html#cb142-2" aria-hidden="true"></a><span class="op">&gt;</span><span class="st"> </span>x1 &lt;-<span class="st"> </span><span class="kw">runif</span>(<span class="dv">100</span>)</span>
<span id="cb142-3"><a href="linear-regression.html#cb142-3" aria-hidden="true"></a><span class="op">&gt;</span><span class="st"> </span>x2 &lt;-<span class="st"> </span><span class="fl">0.5</span> <span class="op">*</span><span class="st"> </span>x1 <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">/</span><span class="st"> </span><span class="dv">10</span></span>
<span id="cb142-4"><a href="linear-regression.html#cb142-4" aria-hidden="true"></a><span class="op">&gt;</span><span class="st"> </span>y &lt;-<span class="st"> </span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>x1 <span class="op">+</span><span class="st"> </span><span class="fl">0.3</span> <span class="op">*</span><span class="st"> </span>x2 <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span></code></pre></div>
<p>The last line corresponds to creating a linear model in which <code>y</code> is a
function of <code>x1</code> and <code>x2</code>. Write out the form of the linear model. What are
the regression coefficients?</p></li>
</ol>
</blockquote>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="linear-regression.html#cb143-1" aria-hidden="true"></a><span class="kw">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb143-2"><a href="linear-regression.html#cb143-2" aria-hidden="true"></a>x1 &lt;-<span class="st"> </span><span class="kw">runif</span>(<span class="dv">100</span>)</span>
<span id="cb143-3"><a href="linear-regression.html#cb143-3" aria-hidden="true"></a>x2 &lt;-<span class="st"> </span><span class="fl">0.5</span> <span class="op">*</span><span class="st"> </span>x1 <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="op">/</span><span class="st"> </span><span class="dv">10</span></span>
<span id="cb143-4"><a href="linear-regression.html#cb143-4" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>x1 <span class="op">+</span><span class="st"> </span><span class="fl">0.3</span> <span class="op">*</span><span class="st"> </span>x2 <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span></code></pre></div>
<p>The model is of the form:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1X_1 + \beta_2X_2 + \epsilon\]</span></p>
<p>The coefficients are <span class="math inline">\(\beta_0 = 2\)</span>, <span class="math inline">\(\beta_1 = 2\)</span>, <span class="math inline">\(\beta_3 = 0.3\)</span>.</p>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>What is the correlation between <code>x1</code> and <code>x2</code>? Create a scatterplot
displaying the relationship between the variables.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="linear-regression.html#cb144-1" aria-hidden="true"></a><span class="kw">cor</span>(x1, x2)</span></code></pre></div>
<pre><code>## [1] 0.8351212</code></pre>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="linear-regression.html#cb146-1" aria-hidden="true"></a><span class="kw">plot</span>(x1, x2)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Using this data, fit a least squares regression to predict <code>y</code> using <code>x1</code>
and <code>x2</code>. Describe the results obtained. What are <span class="math inline">\(\hat\beta_0\)</span>,
<span class="math inline">\(\hat\beta_1\)</span>, and <span class="math inline">\(\hat\beta_2\)</span>? How do these relate to the true <span class="math inline">\(\beta_0\)</span>,
<span class="math inline">\(\beta_1\)</span>, and _2$? Can you reject the null hypothesis <span class="math inline">\(H_0 : \beta_1\)</span>
= 0$? How about the null hypothesis <span class="math inline">\(H_0 : \beta_2 = 0\)</span>?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="linear-regression.html#cb147-1" aria-hidden="true"></a><span class="kw">summary</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x1 <span class="op">+</span><span class="st"> </span>x2))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1 + x2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.8311 -0.7273 -0.0537  0.6338  2.3359 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.1305     0.2319   9.188 7.61e-15 ***
## x1            1.4396     0.7212   1.996   0.0487 *  
## x2            1.0097     1.1337   0.891   0.3754    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.056 on 97 degrees of freedom
## Multiple R-squared:  0.2088, Adjusted R-squared:  0.1925 
## F-statistic:  12.8 on 2 and 97 DF,  p-value: 1.164e-05</code></pre>
<p><span class="math inline">\(\hat\beta_0 = 2.13\)</span>, <span class="math inline">\(\hat\beta_1 = 1.43\)</span>, and <span class="math inline">\(\hat\beta_2 = 1.01\)</span>. These are
relatively poor estimates of the true values. We can reject the hypothesis that
<span class="math inline">\(H_0 : \beta_1\)</span> at a p-value of 0.05 (just about). We cannot reject the
hypothesis that <span class="math inline">\(H_0 : \beta_2 = 0\)</span>.</p>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Now fit a least squares regression to predict <code>y</code> using only <code>x1</code>. Comment
on your results. Can you reject the null hypothesis <span class="math inline">\(H 0 : \beta_1 = 0\)</span>?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="linear-regression.html#cb149-1" aria-hidden="true"></a><span class="kw">summary</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x1))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.89495 -0.66874 -0.07785  0.59221  2.45560 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.1124     0.2307   9.155 8.27e-15 ***
## x1            1.9759     0.3963   4.986 2.66e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.055 on 98 degrees of freedom
## Multiple R-squared:  0.2024, Adjusted R-squared:  0.1942 
## F-statistic: 24.86 on 1 and 98 DF,  p-value: 2.661e-06</code></pre>
<p>We can reject <span class="math inline">\(H_0 : \beta_1 = 0\)</span>. The p-value is much more significant for
<span class="math inline">\(\beta_1\)</span> compared to when <code>x2</code> is included in the model.</p>
<blockquote>
<ol start="5" style="list-style-type: lower-alpha">
<li>Now fit a least squares regression to predict <code>y</code> using only <code>x2</code>. Comment
on your results. Can you reject the null hypothesis <span class="math inline">\(H_0 : \beta_1 = 0\)</span>?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="linear-regression.html#cb151-1" aria-hidden="true"></a><span class="kw">summary</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x2))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.62687 -0.75156 -0.03598  0.72383  2.44890 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.3899     0.1949   12.26  &lt; 2e-16 ***
## x2            2.8996     0.6330    4.58 1.37e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.072 on 98 degrees of freedom
## Multiple R-squared:  0.1763, Adjusted R-squared:  0.1679 
## F-statistic: 20.98 on 1 and 98 DF,  p-value: 1.366e-05</code></pre>
<p>Similarly, we can reject <span class="math inline">\(H_0 : \beta_2 = 0\)</span>. The p-value is much more
significant for <span class="math inline">\(\beta_2\)</span> compared to when <code>x1</code> is included in the model.</p>
<blockquote>
<ol start="6" style="list-style-type: lower-alpha">
<li>Do the results obtained in (c)–(e) contradict each other? Explain your
answer.</li>
</ol>
</blockquote>
<p>No they do not contradict each other. Both <code>x1</code> and <code>x2</code> individually are
capable of explaining much of the variation observed in <code>y</code>, however since they
are correlated, it is very difficult to tease apart their separate
contributions.</p>
<blockquote>
<ol start="7" style="list-style-type: lower-alpha">
<li><p>Now suppose we obtain one additional observation, which was unfortunately
mismeasured.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="linear-regression.html#cb153-1" aria-hidden="true"></a><span class="op">&gt;</span><span class="st"> </span>x1 &lt;-<span class="st"> </span><span class="kw">c</span>(x1, <span class="fl">0.1</span>)</span>
<span id="cb153-2"><a href="linear-regression.html#cb153-2" aria-hidden="true"></a><span class="op">&gt;</span><span class="st"> </span>x2 &lt;-<span class="st"> </span><span class="kw">c</span>(x2, <span class="fl">0.8</span>)</span>
<span id="cb153-3"><a href="linear-regression.html#cb153-3" aria-hidden="true"></a><span class="op">&gt;</span><span class="st"> </span>y &lt;-<span class="st"> </span><span class="kw">c</span>(y, <span class="dv">6</span>)</span></code></pre></div>
<p>Re-fit the linear models from (c) to (e) using this new data. What effect
does this new observation have on the each of the models? In each model, is
this observation an outlier? A high-leverage point? Both? Explain your
answers.</p></li>
</ol>
</blockquote>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="linear-regression.html#cb154-1" aria-hidden="true"></a>x1 &lt;-<span class="st"> </span><span class="kw">c</span>(x1 , <span class="fl">0.1</span>)</span>
<span id="cb154-2"><a href="linear-regression.html#cb154-2" aria-hidden="true"></a>x2 &lt;-<span class="st"> </span><span class="kw">c</span>(x2 , <span class="fl">0.8</span>)</span>
<span id="cb154-3"><a href="linear-regression.html#cb154-3" aria-hidden="true"></a>y &lt;-<span class="st"> </span><span class="kw">c</span>(y ,<span class="dv">6</span>)</span>
<span id="cb154-4"><a href="linear-regression.html#cb154-4" aria-hidden="true"></a><span class="kw">summary</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x1 <span class="op">+</span><span class="st"> </span>x2))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1 + x2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.73348 -0.69318 -0.05263  0.66385  2.30619 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.2267     0.2314   9.624 7.91e-16 ***
## x1            0.5394     0.5922   0.911  0.36458    
## x2            2.5146     0.8977   2.801  0.00614 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.075 on 98 degrees of freedom
## Multiple R-squared:  0.2188, Adjusted R-squared:  0.2029 
## F-statistic: 13.72 on 2 and 98 DF,  p-value: 5.564e-06</code></pre>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="linear-regression.html#cb156-1" aria-hidden="true"></a><span class="kw">summary</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x1))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.8897 -0.6556 -0.0909  0.5682  3.5665 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.2569     0.2390   9.445 1.78e-15 ***
## x1            1.7657     0.4124   4.282 4.29e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.111 on 99 degrees of freedom
## Multiple R-squared:  0.1562, Adjusted R-squared:  0.1477 
## F-statistic: 18.33 on 1 and 99 DF,  p-value: 4.295e-05</code></pre>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="linear-regression.html#cb158-1" aria-hidden="true"></a><span class="kw">summary</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x2))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.64729 -0.71021 -0.06899  0.72699  2.38074 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.3451     0.1912  12.264  &lt; 2e-16 ***
## x2            3.1190     0.6040   5.164 1.25e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.074 on 99 degrees of freedom
## Multiple R-squared:  0.2122, Adjusted R-squared:  0.2042 
## F-statistic: 26.66 on 1 and 99 DF,  p-value: 1.253e-06</code></pre>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="linear-regression.html#cb160-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb160-2"><a href="linear-regression.html#cb160-2" aria-hidden="true"></a><span class="kw">plot</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x1 <span class="op">+</span><span class="st"> </span>x2), <span class="dt">cex =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-43-1.png" width="672" /></p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="linear-regression.html#cb161-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb161-2"><a href="linear-regression.html#cb161-2" aria-hidden="true"></a><span class="kw">plot</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x1), <span class="dt">cex =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-43-2.png" width="672" /></p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="linear-regression.html#cb162-1" aria-hidden="true"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb162-2"><a href="linear-regression.html#cb162-2" aria-hidden="true"></a><span class="kw">plot</span>(<span class="kw">lm</span>(y <span class="op">~</span><span class="st"> </span>x2), <span class="dt">cex =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-43-3.png" width="672" /></p>
<p>In the first model (with both predictors), the new point has very high leverage
(since it is an outlier in terms of the joint <code>x1</code> and <code>x2</code> distribution),
however it is not an outlier. In the model that includes <code>x1</code>, it is an outlier
but does not have high leverage. In the model that includes <code>x2</code>, it has high
leverage but is not an outlier. It is useful to consider the scatterplot of
<code>x1</code> and <code>x2</code>.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="linear-regression.html#cb163-1" aria-hidden="true"></a><span class="kw">plot</span>(x1, x2)</span>
<span id="cb163-2"><a href="linear-regression.html#cb163-2" aria-hidden="true"></a><span class="kw">points</span>(<span class="fl">0.1</span>, <span class="fl">0.8</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">pch =</span> <span class="dv">19</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
</div>
<div id="question-15" class="section level3 hasAnchor" number="3.2.8">
<h3><span class="header-section-number">3.2.8</span> Question 15<a href="linear-regression.html#question-15" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>This problem involves the <code>Boston</code> data set, which we saw in the lab for this
chapter. We will now try to predict per capita crime rate using the other
variables in this data set. In other words, per capita crime rate is the
response, and the other variables are the predictors.</p>
</blockquote>
<p>We are trying to predict <code>crim</code>.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="linear-regression.html#cb164-1" aria-hidden="true"></a>pred &lt;-<span class="st"> </span><span class="kw">subset</span>(Boston, <span class="dt">select =</span> <span class="op">-</span>crim)</span></code></pre></div>
<blockquote>
<ol style="list-style-type: lower-alpha">
<li>For each predictor, fit a simple linear regression model to predict the
response. Describe your results. In which of the models is there a
statistically significant association between the predictor and the
response? Create some plots to back up your assertions.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="linear-regression.html#cb165-1" aria-hidden="true"></a>fits &lt;-<span class="st"> </span><span class="kw">lapply</span>(pred, <span class="cf">function</span>(x) <span class="kw">lm</span>(Boston<span class="op">$</span>crim <span class="op">~</span><span class="st"> </span>x))</span>
<span id="cb165-2"><a href="linear-regression.html#cb165-2" aria-hidden="true"></a><span class="kw">printCoefmat</span>(<span class="kw">do.call</span>(rbind, <span class="kw">lapply</span>(fits, <span class="cf">function</span>(x) <span class="kw">coef</span>(<span class="kw">summary</span>(x))[<span class="dv">2</span>, ])))</span></code></pre></div>
<pre><code>##           Estimate Std. Error t value  Pr(&gt;|t|)    
## zn      -0.0739350  0.0160946 -4.5938 5.506e-06 ***
## indus    0.5097763  0.0510243  9.9908 &lt; 2.2e-16 ***
## chas    -1.8927766  1.5061155 -1.2567    0.2094    
## nox     31.2485312  2.9991904 10.4190 &lt; 2.2e-16 ***
## rm      -2.6840512  0.5320411 -5.0448 6.347e-07 ***
## age      0.1077862  0.0127364  8.4628 2.855e-16 ***
## dis     -1.5509017  0.1683300 -9.2135 &lt; 2.2e-16 ***
## rad      0.6179109  0.0343318 17.9982 &lt; 2.2e-16 ***
## tax      0.0297423  0.0018474 16.0994 &lt; 2.2e-16 ***
## ptratio  1.1519828  0.1693736  6.8014 2.943e-11 ***
## lstat    0.5488048  0.0477610 11.4907 &lt; 2.2e-16 ***
## medv    -0.3631599  0.0383902 -9.4597 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>There are significant associations for all predictors with the exception of
<code>chas</code> when fitting separate linear models. For example, consider the following
plot representing the third model</p>
<pre><code>plot(Boston$rm, Boston$crim)
abline(fits[[5]])</code></pre>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Fit a multiple regression model to predict the response using all of the
predictors. Describe your results. For which predictors can we reject the
null hypothesis <span class="math inline">\(H_0 : \beta_j = 0\)</span>?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="linear-regression.html#cb168-1" aria-hidden="true"></a>mfit &lt;-<span class="st"> </span><span class="kw">lm</span>(crim <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> Boston)</span>
<span id="cb168-2"><a href="linear-regression.html#cb168-2" aria-hidden="true"></a><span class="kw">summary</span>(mfit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = crim ~ ., data = Boston)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.534 -2.248 -0.348  1.087 73.923 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 13.7783938  7.0818258   1.946 0.052271 .  
## zn           0.0457100  0.0187903   2.433 0.015344 *  
## indus       -0.0583501  0.0836351  -0.698 0.485709    
## chas        -0.8253776  1.1833963  -0.697 0.485841    
## nox         -9.9575865  5.2898242  -1.882 0.060370 .  
## rm           0.6289107  0.6070924   1.036 0.300738    
## age         -0.0008483  0.0179482  -0.047 0.962323    
## dis         -1.0122467  0.2824676  -3.584 0.000373 ***
## rad          0.6124653  0.0875358   6.997 8.59e-12 ***
## tax         -0.0037756  0.0051723  -0.730 0.465757    
## ptratio     -0.3040728  0.1863598  -1.632 0.103393    
## lstat        0.1388006  0.0757213   1.833 0.067398 .  
## medv        -0.2200564  0.0598240  -3.678 0.000261 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.46 on 493 degrees of freedom
## Multiple R-squared:  0.4493, Adjusted R-squared:  0.4359 
## F-statistic: 33.52 on 12 and 493 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>There are now only significant associations for <code>zn</code>, <code>dis</code>, <code>rad</code>, <code>black</code> and
<code>medv</code>.</p>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>How do your results from (a) compare to your results from (b)? Create a
plot displaying the univariate regression coefficients from (a) on the
<span class="math inline">\(x\)</span>-axis, and the multiple regression coefficients from (b) on the
<span class="math inline">\(y\)</span>-axis. That is, each predictor is displayed as a single point in the
plot. Its coefficient in a simple linear regression model is shown on the
x-axis, and its coefficient estimate in the multiple linear regression
model is shown on the y-axis.</li>
</ol>
</blockquote>
<p>The results from (b) show reduced significance compared to the models fit in
(a).</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="linear-regression.html#cb170-1" aria-hidden="true"></a><span class="kw">plot</span>(<span class="kw">sapply</span>(fits, <span class="cf">function</span>(x) <span class="kw">coef</span>(x)[<span class="dv">2</span>]), <span class="kw">coef</span>(mfit)[<span class="op">-</span><span class="dv">1</span>], </span>
<span id="cb170-2"><a href="linear-regression.html#cb170-2" aria-hidden="true"></a>  <span class="dt">xlab =</span> <span class="st">&quot;Univariate regression&quot;</span>, </span>
<span id="cb170-3"><a href="linear-regression.html#cb170-3" aria-hidden="true"></a>  <span class="dt">ylab =</span> <span class="st">&quot;multiple regression&quot;</span>)</span></code></pre></div>
<p><img src="03-linear-regression_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>The estimated coefficients differ (in particular the estimated coefficient for
<code>nox</code> is dramatically different) between the two modelling strategies.</p>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Is there evidence of non-linear association between any of the predictors
and the response? To answer this question, for each predictor X, fit a
model of the form
<span class="math display">\[
Y = \beta_0 + \beta_1X + \beta_2X^2 + \beta_3X^3 + \epsilon
\]</span></li>
</ol>
</blockquote>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="linear-regression.html#cb171-1" aria-hidden="true"></a>pred &lt;-<span class="st"> </span><span class="kw">subset</span>(pred, <span class="dt">select =</span> <span class="op">-</span>chas)</span>
<span id="cb171-2"><a href="linear-regression.html#cb171-2" aria-hidden="true"></a>fits &lt;-<span class="st"> </span><span class="kw">lapply</span>(<span class="kw">names</span>(pred), <span class="cf">function</span>(p) {</span>
<span id="cb171-3"><a href="linear-regression.html#cb171-3" aria-hidden="true"></a>  f &lt;-<span class="st"> </span><span class="kw">paste0</span>(<span class="st">&quot;crim ~ poly(&quot;</span>, p, <span class="st">&quot;, 3)&quot;</span>)</span>
<span id="cb171-4"><a href="linear-regression.html#cb171-4" aria-hidden="true"></a>  <span class="kw">lm</span>(<span class="kw">as.formula</span>(f), <span class="dt">data =</span> Boston)</span>
<span id="cb171-5"><a href="linear-regression.html#cb171-5" aria-hidden="true"></a>})</span>
<span id="cb171-6"><a href="linear-regression.html#cb171-6" aria-hidden="true"></a><span class="cf">for</span> (fit <span class="cf">in</span> fits) <span class="kw">printCoefmat</span>(<span class="kw">coef</span>(<span class="kw">summary</span>(fit)))</span></code></pre></div>
<pre><code>##               Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)    3.61352    0.37219  9.7088 &lt; 2.2e-16 ***
## poly(zn, 3)1 -38.74984    8.37221 -4.6284 4.698e-06 ***
## poly(zn, 3)2  23.93983    8.37221  2.8594  0.004421 ** 
## poly(zn, 3)3 -10.07187    8.37221 -1.2030  0.229539    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##                 Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)       3.6135     0.3300 10.9501 &lt; 2.2e-16 ***
## poly(indus, 3)1  78.5908     7.4231 10.5873 &lt; 2.2e-16 ***
## poly(indus, 3)2 -24.3948     7.4231 -3.2863  0.001086 ** 
## poly(indus, 3)3 -54.1298     7.4231 -7.2920 1.196e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##                Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)     3.61352    0.32157 11.2370 &lt; 2.2e-16 ***
## poly(nox, 3)1  81.37202    7.23361 11.2492 &lt; 2.2e-16 ***
## poly(nox, 3)2 -28.82859    7.23361 -3.9854 7.737e-05 ***
## poly(nox, 3)3 -60.36189    7.23361 -8.3446 6.961e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##              Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)    3.6135     0.3703  9.7584 &lt; 2.2e-16 ***
## poly(rm, 3)1 -42.3794     8.3297 -5.0878 5.128e-07 ***
## poly(rm, 3)2  26.5768     8.3297  3.1906  0.001509 ** 
## poly(rm, 3)3  -5.5103     8.3297 -0.6615  0.508575    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##               Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)    3.61352    0.34852 10.3683 &lt; 2.2e-16 ***
## poly(age, 3)1 68.18201    7.83970  8.6970 &lt; 2.2e-16 ***
## poly(age, 3)2 37.48447    7.83970  4.7814 2.291e-06 ***
## poly(age, 3)3 21.35321    7.83970  2.7237   0.00668 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##                Estimate Std. Error  t value  Pr(&gt;|t|)    
## (Intercept)     3.61352    0.32592  11.0870 &lt; 2.2e-16 ***
## poly(dis, 3)1 -73.38859    7.33148 -10.0101 &lt; 2.2e-16 ***
## poly(dis, 3)2  56.37304    7.33148   7.6892 7.870e-14 ***
## poly(dis, 3)3 -42.62188    7.33148  -5.8135 1.089e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##                Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)     3.61352    0.29707 12.1639 &lt; 2.2e-16 ***
## poly(rad, 3)1 120.90745    6.68240 18.0934 &lt; 2.2e-16 ***
## poly(rad, 3)2  17.49230    6.68240  2.6177  0.009121 ** 
## poly(rad, 3)3   4.69846    6.68240  0.7031  0.482314    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##                Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)     3.61352    0.30468 11.8599 &lt; 2.2e-16 ***
## poly(tax, 3)1 112.64583    6.85371 16.4358 &lt; 2.2e-16 ***
## poly(tax, 3)2  32.08725    6.85371  4.6817 3.665e-06 ***
## poly(tax, 3)3  -7.99681    6.85371 -1.1668    0.2439    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##                    Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)         3.61352    0.36105 10.0084 &lt; 2.2e-16 ***
## poly(ptratio, 3)1  56.04523    8.12158  6.9008 1.565e-11 ***
## poly(ptratio, 3)2  24.77482    8.12158  3.0505  0.002405 ** 
## poly(ptratio, 3)3 -22.27974    8.12158 -2.7433  0.006301 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       3.61352    0.33917 10.6540   &lt;2e-16 ***
## poly(lstat, 3)1  88.06967    7.62944 11.5434   &lt;2e-16 ***
## poly(lstat, 3)2  15.88816    7.62944  2.0825   0.0378 *  
## poly(lstat, 3)3 -11.57402    7.62944 -1.5170   0.1299    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##                 Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)      3.61352    0.29203  12.374 &lt; 2.2e-16 ***
## poly(medv, 3)1 -75.05761    6.56915 -11.426 &lt; 2.2e-16 ***
## poly(medv, 3)2  88.08621    6.56915  13.409 &lt; 2.2e-16 ***
## poly(medv, 3)3 -48.03343    6.56915  -7.312 1.047e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Yes there is strong evidence for many variables having non-linear associations.
In many cases, the addition of a cubic term is significant (<code>indus</code>, <code>nox</code>,
<code>age</code>, <code>dis</code>, <code>ptratio</code> and <code>medv</code>). In other cases although the cubic terms
is not significant, the squared term is (<code>zn</code>, <code>rm</code>, <code>rad</code>, <code>tax</code>, <code>lstat</code>).
In only one case, <code>black</code> is there no evidence for a non-linear relationship.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="statistical-learning.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="classification.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": {}
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/danhalligan/ISLRv2-solutions/edit/master/03-linear-regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
