<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Resampling Methods | An Introduction to Statistical Learning</title>
  <meta name="description" content="5 Resampling Methods | An Introduction to Statistical Learning" />
  <meta name="generator" content="bookdown 0.29.3 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Resampling Methods | An Introduction to Statistical Learning" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Resampling Methods | An Introduction to Statistical Learning" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="classification.html"/>
<link rel="next" href="linear-model-selection-and-regularization.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="islrv2.css" type="text/css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/aaaakshat/cm-web-fonts@latest/fonts.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">ISLRv2 Solutions</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="statistical-learning.html"><a href="statistical-learning.html"><i class="fa fa-check"></i><b>2</b> Statistical Learning</a><ul>
<li class="chapter" data-level="2.1" data-path="statistical-learning.html"><a href="statistical-learning.html#conceptual"><i class="fa fa-check"></i><b>2.1</b> Conceptual</a><ul>
<li class="chapter" data-level="2.1.1" data-path="statistical-learning.html"><a href="statistical-learning.html#question-1"><i class="fa fa-check"></i><b>2.1.1</b> Question 1</a></li>
<li class="chapter" data-level="2.1.2" data-path="statistical-learning.html"><a href="statistical-learning.html#question-2"><i class="fa fa-check"></i><b>2.1.2</b> Question 2</a></li>
<li class="chapter" data-level="2.1.3" data-path="statistical-learning.html"><a href="statistical-learning.html#question-3"><i class="fa fa-check"></i><b>2.1.3</b> Question 3</a></li>
<li class="chapter" data-level="2.1.4" data-path="statistical-learning.html"><a href="statistical-learning.html#question-4"><i class="fa fa-check"></i><b>2.1.4</b> Question 4</a></li>
<li class="chapter" data-level="2.1.5" data-path="statistical-learning.html"><a href="statistical-learning.html#question-5"><i class="fa fa-check"></i><b>2.1.5</b> Question 5</a></li>
<li class="chapter" data-level="2.1.6" data-path="statistical-learning.html"><a href="statistical-learning.html#question-6"><i class="fa fa-check"></i><b>2.1.6</b> Question 6</a></li>
<li class="chapter" data-level="2.1.7" data-path="statistical-learning.html"><a href="statistical-learning.html#question-7"><i class="fa fa-check"></i><b>2.1.7</b> Question 7</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="statistical-learning.html"><a href="statistical-learning.html#applied"><i class="fa fa-check"></i><b>2.2</b> Applied</a><ul>
<li class="chapter" data-level="2.2.1" data-path="statistical-learning.html"><a href="statistical-learning.html#question-8"><i class="fa fa-check"></i><b>2.2.1</b> Question 8</a></li>
<li class="chapter" data-level="2.2.2" data-path="statistical-learning.html"><a href="statistical-learning.html#question-9"><i class="fa fa-check"></i><b>2.2.2</b> Question 9</a></li>
<li class="chapter" data-level="2.2.3" data-path="statistical-learning.html"><a href="statistical-learning.html#question-10"><i class="fa fa-check"></i><b>2.2.3</b> Question 10</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i><b>3</b> Linear Regression</a><ul>
<li class="chapter" data-level="3.1" data-path="linear-regression.html"><a href="linear-regression.html#conceptual-1"><i class="fa fa-check"></i><b>3.1</b> Conceptual</a><ul>
<li class="chapter" data-level="3.1.1" data-path="linear-regression.html"><a href="linear-regression.html#question-1-1"><i class="fa fa-check"></i><b>3.1.1</b> Question 1</a></li>
<li class="chapter" data-level="3.1.2" data-path="linear-regression.html"><a href="linear-regression.html#question-2-1"><i class="fa fa-check"></i><b>3.1.2</b> Question 2</a></li>
<li class="chapter" data-level="3.1.3" data-path="linear-regression.html"><a href="linear-regression.html#question-3-1"><i class="fa fa-check"></i><b>3.1.3</b> Question 3</a></li>
<li class="chapter" data-level="3.1.4" data-path="linear-regression.html"><a href="linear-regression.html#question-4-1"><i class="fa fa-check"></i><b>3.1.4</b> Question 4</a></li>
<li class="chapter" data-level="3.1.5" data-path="linear-regression.html"><a href="linear-regression.html#question-5-1"><i class="fa fa-check"></i><b>3.1.5</b> Question 5</a></li>
<li class="chapter" data-level="3.1.6" data-path="linear-regression.html"><a href="linear-regression.html#question-6-1"><i class="fa fa-check"></i><b>3.1.6</b> Question 6</a></li>
<li class="chapter" data-level="3.1.7" data-path="linear-regression.html"><a href="linear-regression.html#question-7-1"><i class="fa fa-check"></i><b>3.1.7</b> Question 7</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="linear-regression.html"><a href="linear-regression.html#applied-1"><i class="fa fa-check"></i><b>3.2</b> Applied</a><ul>
<li class="chapter" data-level="3.2.1" data-path="linear-regression.html"><a href="linear-regression.html#question-8-1"><i class="fa fa-check"></i><b>3.2.1</b> Question 8</a></li>
<li class="chapter" data-level="3.2.2" data-path="linear-regression.html"><a href="linear-regression.html#question-9-1"><i class="fa fa-check"></i><b>3.2.2</b> Question 9</a></li>
<li class="chapter" data-level="3.2.3" data-path="linear-regression.html"><a href="linear-regression.html#question-10-1"><i class="fa fa-check"></i><b>3.2.3</b> Question 10</a></li>
<li class="chapter" data-level="3.2.4" data-path="linear-regression.html"><a href="linear-regression.html#question-11"><i class="fa fa-check"></i><b>3.2.4</b> Question 11</a></li>
<li class="chapter" data-level="3.2.5" data-path="linear-regression.html"><a href="linear-regression.html#question-12"><i class="fa fa-check"></i><b>3.2.5</b> Question 12</a></li>
<li class="chapter" data-level="3.2.6" data-path="linear-regression.html"><a href="linear-regression.html#question-13"><i class="fa fa-check"></i><b>3.2.6</b> Question 13</a></li>
<li class="chapter" data-level="3.2.7" data-path="linear-regression.html"><a href="linear-regression.html#question-14"><i class="fa fa-check"></i><b>3.2.7</b> Question 14</a></li>
<li class="chapter" data-level="3.2.8" data-path="linear-regression.html"><a href="linear-regression.html#question-15"><i class="fa fa-check"></i><b>3.2.8</b> Question 15</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>4</b> Classification</a><ul>
<li class="chapter" data-level="4.1" data-path="classification.html"><a href="classification.html#conceptual-2"><i class="fa fa-check"></i><b>4.1</b> Conceptual</a><ul>
<li class="chapter" data-level="4.1.1" data-path="classification.html"><a href="classification.html#question-1-2"><i class="fa fa-check"></i><b>4.1.1</b> Question 1</a></li>
<li class="chapter" data-level="4.1.2" data-path="classification.html"><a href="classification.html#question-2-2"><i class="fa fa-check"></i><b>4.1.2</b> Question 2</a></li>
<li class="chapter" data-level="4.1.3" data-path="classification.html"><a href="classification.html#question-3-2"><i class="fa fa-check"></i><b>4.1.3</b> Question 3</a></li>
<li class="chapter" data-level="4.1.4" data-path="classification.html"><a href="classification.html#question-4-2"><i class="fa fa-check"></i><b>4.1.4</b> Question 4</a></li>
<li class="chapter" data-level="4.1.5" data-path="classification.html"><a href="classification.html#question-5-2"><i class="fa fa-check"></i><b>4.1.5</b> Question 5</a></li>
<li class="chapter" data-level="4.1.6" data-path="classification.html"><a href="classification.html#question-6-2"><i class="fa fa-check"></i><b>4.1.6</b> Question 6</a></li>
<li class="chapter" data-level="4.1.7" data-path="classification.html"><a href="classification.html#question-7-2"><i class="fa fa-check"></i><b>4.1.7</b> Question 7</a></li>
<li class="chapter" data-level="4.1.8" data-path="classification.html"><a href="classification.html#question-8-2"><i class="fa fa-check"></i><b>4.1.8</b> Question 8</a></li>
<li class="chapter" data-level="4.1.9" data-path="classification.html"><a href="classification.html#question-9-2"><i class="fa fa-check"></i><b>4.1.9</b> Question 9</a></li>
<li class="chapter" data-level="4.1.10" data-path="classification.html"><a href="classification.html#question-10-2"><i class="fa fa-check"></i><b>4.1.10</b> Question 10</a></li>
<li class="chapter" data-level="4.1.11" data-path="classification.html"><a href="classification.html#question-11-1"><i class="fa fa-check"></i><b>4.1.11</b> Question 11</a></li>
<li class="chapter" data-level="4.1.12" data-path="classification.html"><a href="classification.html#question-12-1"><i class="fa fa-check"></i><b>4.1.12</b> Question 12</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="classification.html"><a href="classification.html#applied-2"><i class="fa fa-check"></i><b>4.2</b> Applied</a><ul>
<li class="chapter" data-level="4.2.1" data-path="classification.html"><a href="classification.html#question-13-1"><i class="fa fa-check"></i><b>4.2.1</b> Question 13</a></li>
<li class="chapter" data-level="4.2.2" data-path="classification.html"><a href="classification.html#question-14-1"><i class="fa fa-check"></i><b>4.2.2</b> Question 14</a></li>
<li class="chapter" data-level="4.2.3" data-path="classification.html"><a href="classification.html#question-15-1"><i class="fa fa-check"></i><b>4.2.3</b> Question 15</a></li>
<li class="chapter" data-level="4.2.4" data-path="classification.html"><a href="classification.html#question-13-2"><i class="fa fa-check"></i><b>4.2.4</b> Question 13</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="resampling-methods.html"><a href="resampling-methods.html"><i class="fa fa-check"></i><b>5</b> Resampling Methods</a><ul>
<li class="chapter" data-level="5.1" data-path="resampling-methods.html"><a href="resampling-methods.html#conceptual-3"><i class="fa fa-check"></i><b>5.1</b> Conceptual</a><ul>
<li class="chapter" data-level="5.1.1" data-path="resampling-methods.html"><a href="resampling-methods.html#question-1-3"><i class="fa fa-check"></i><b>5.1.1</b> Question 1</a></li>
<li class="chapter" data-level="5.1.2" data-path="resampling-methods.html"><a href="resampling-methods.html#question-2-3"><i class="fa fa-check"></i><b>5.1.2</b> Question 2</a></li>
<li class="chapter" data-level="5.1.3" data-path="resampling-methods.html"><a href="resampling-methods.html#question-3-3"><i class="fa fa-check"></i><b>5.1.3</b> Question 3</a></li>
<li class="chapter" data-level="5.1.4" data-path="resampling-methods.html"><a href="resampling-methods.html#question-4-3"><i class="fa fa-check"></i><b>5.1.4</b> Question 4</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="resampling-methods.html"><a href="resampling-methods.html#applied-3"><i class="fa fa-check"></i><b>5.2</b> Applied</a><ul>
<li class="chapter" data-level="5.2.1" data-path="resampling-methods.html"><a href="resampling-methods.html#question-5-3"><i class="fa fa-check"></i><b>5.2.1</b> Question 5</a></li>
<li class="chapter" data-level="5.2.2" data-path="resampling-methods.html"><a href="resampling-methods.html#question-6-3"><i class="fa fa-check"></i><b>5.2.2</b> Question 6</a></li>
<li class="chapter" data-level="5.2.3" data-path="resampling-methods.html"><a href="resampling-methods.html#question-7-3"><i class="fa fa-check"></i><b>5.2.3</b> Question 7</a></li>
<li class="chapter" data-level="5.2.4" data-path="resampling-methods.html"><a href="resampling-methods.html#question-8-3"><i class="fa fa-check"></i><b>5.2.4</b> Question 8</a></li>
<li class="chapter" data-level="5.2.5" data-path="resampling-methods.html"><a href="resampling-methods.html#question-9-3"><i class="fa fa-check"></i><b>5.2.5</b> Question 9</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html"><i class="fa fa-check"></i><b>6</b> Linear Model Selection and Regularization</a><ul>
<li class="chapter" data-level="6.1" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#conceptual-4"><i class="fa fa-check"></i><b>6.1</b> Conceptual</a><ul>
<li class="chapter" data-level="6.1.1" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-1-4"><i class="fa fa-check"></i><b>6.1.1</b> Question 1</a></li>
<li class="chapter" data-level="6.1.2" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-2-4"><i class="fa fa-check"></i><b>6.1.2</b> Question 2</a></li>
<li class="chapter" data-level="6.1.3" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-3-4"><i class="fa fa-check"></i><b>6.1.3</b> Question 3</a></li>
<li class="chapter" data-level="6.1.4" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-4-4"><i class="fa fa-check"></i><b>6.1.4</b> Question 4</a></li>
<li class="chapter" data-level="6.1.5" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-5-4"><i class="fa fa-check"></i><b>6.1.5</b> Question 5</a></li>
<li class="chapter" data-level="6.1.6" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-6-4"><i class="fa fa-check"></i><b>6.1.6</b> Question 6</a></li>
<li class="chapter" data-level="6.1.7" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-7-4"><i class="fa fa-check"></i><b>6.1.7</b> Question 7</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#applied-4"><i class="fa fa-check"></i><b>6.2</b> Applied</a><ul>
<li class="chapter" data-level="6.2.1" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-8-4"><i class="fa fa-check"></i><b>6.2.1</b> Question 8</a></li>
<li class="chapter" data-level="6.2.2" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-9-4"><i class="fa fa-check"></i><b>6.2.2</b> Question 9</a></li>
<li class="chapter" data-level="6.2.3" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-10-3"><i class="fa fa-check"></i><b>6.2.3</b> Question 10</a></li>
<li class="chapter" data-level="6.2.4" data-path="linear-model-selection-and-regularization.html"><a href="linear-model-selection-and-regularization.html#question-11-2"><i class="fa fa-check"></i><b>6.2.4</b> Question 11</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html"><i class="fa fa-check"></i><b>7</b> Moving Beyond Linearity</a><ul>
<li class="chapter" data-level="7.1" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#conceptual-5"><i class="fa fa-check"></i><b>7.1</b> Conceptual</a><ul>
<li class="chapter" data-level="7.1.1" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-1-5"><i class="fa fa-check"></i><b>7.1.1</b> Question 1</a></li>
<li class="chapter" data-level="7.1.2" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-2-5"><i class="fa fa-check"></i><b>7.1.2</b> Question 2</a></li>
<li class="chapter" data-level="7.1.3" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-3-5"><i class="fa fa-check"></i><b>7.1.3</b> Question 3</a></li>
<li class="chapter" data-level="7.1.4" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-4-5"><i class="fa fa-check"></i><b>7.1.4</b> Question 4</a></li>
<li class="chapter" data-level="7.1.5" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-5-5"><i class="fa fa-check"></i><b>7.1.5</b> Question 5</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#applied-5"><i class="fa fa-check"></i><b>7.2</b> Applied</a><ul>
<li class="chapter" data-level="7.2.1" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-6-5"><i class="fa fa-check"></i><b>7.2.1</b> Question 6</a></li>
<li class="chapter" data-level="7.2.2" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-7-5"><i class="fa fa-check"></i><b>7.2.2</b> Question 7</a></li>
<li class="chapter" data-level="7.2.3" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-8-5"><i class="fa fa-check"></i><b>7.2.3</b> Question 8</a></li>
<li class="chapter" data-level="7.2.4" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-9-5"><i class="fa fa-check"></i><b>7.2.4</b> Question 9</a></li>
<li class="chapter" data-level="7.2.5" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-10-4"><i class="fa fa-check"></i><b>7.2.5</b> Question 10</a></li>
<li class="chapter" data-level="7.2.6" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-11-3"><i class="fa fa-check"></i><b>7.2.6</b> Question 11</a></li>
<li class="chapter" data-level="7.2.7" data-path="moving-beyond-linearity.html"><a href="moving-beyond-linearity.html#question-12-2"><i class="fa fa-check"></i><b>7.2.7</b> Question 12</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tree-based-methods.html"><a href="tree-based-methods.html"><i class="fa fa-check"></i><b>8</b> Tree-Based Methods</a><ul>
<li class="chapter" data-level="8.1" data-path="tree-based-methods.html"><a href="tree-based-methods.html#conceptual-6"><i class="fa fa-check"></i><b>8.1</b> Conceptual</a><ul>
<li class="chapter" data-level="8.1.1" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-1-6"><i class="fa fa-check"></i><b>8.1.1</b> Question 1</a></li>
<li class="chapter" data-level="8.1.2" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-2-6"><i class="fa fa-check"></i><b>8.1.2</b> Question 2</a></li>
<li class="chapter" data-level="8.1.3" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-3-6"><i class="fa fa-check"></i><b>8.1.3</b> Question 3</a></li>
<li class="chapter" data-level="8.1.4" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-4-6"><i class="fa fa-check"></i><b>8.1.4</b> Question 4</a></li>
<li class="chapter" data-level="8.1.5" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-5-6"><i class="fa fa-check"></i><b>8.1.5</b> Question 5</a></li>
<li class="chapter" data-level="8.1.6" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-6-6"><i class="fa fa-check"></i><b>8.1.6</b> Question 6</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="tree-based-methods.html"><a href="tree-based-methods.html#applied-6"><i class="fa fa-check"></i><b>8.2</b> Applied</a><ul>
<li class="chapter" data-level="8.2.1" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-7-6"><i class="fa fa-check"></i><b>8.2.1</b> Question 7</a></li>
<li class="chapter" data-level="8.2.2" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-8-6"><i class="fa fa-check"></i><b>8.2.2</b> Question 8</a></li>
<li class="chapter" data-level="8.2.3" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-9-6"><i class="fa fa-check"></i><b>8.2.3</b> Question 9</a></li>
<li class="chapter" data-level="8.2.4" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-10-5"><i class="fa fa-check"></i><b>8.2.4</b> Question 10</a></li>
<li class="chapter" data-level="8.2.5" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-11-4"><i class="fa fa-check"></i><b>8.2.5</b> Question 11</a></li>
<li class="chapter" data-level="8.2.6" data-path="tree-based-methods.html"><a href="tree-based-methods.html#question-12-3"><i class="fa fa-check"></i><b>8.2.6</b> Question 12</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="support-vector-machines.html"><a href="support-vector-machines.html"><i class="fa fa-check"></i><b>9</b> Support Vector Machines</a><ul>
<li class="chapter" data-level="9.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#conceptual-7"><i class="fa fa-check"></i><b>9.1</b> Conceptual</a><ul>
<li class="chapter" data-level="9.1.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-1-7"><i class="fa fa-check"></i><b>9.1.1</b> Question 1</a></li>
<li class="chapter" data-level="9.1.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-2-7"><i class="fa fa-check"></i><b>9.1.2</b> Question 2</a></li>
<li class="chapter" data-level="9.1.3" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-3-7"><i class="fa fa-check"></i><b>9.1.3</b> Question 3</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#applied-7"><i class="fa fa-check"></i><b>9.2</b> Applied</a><ul>
<li class="chapter" data-level="9.2.1" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-4-7"><i class="fa fa-check"></i><b>9.2.1</b> Question 4</a></li>
<li class="chapter" data-level="9.2.2" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-5-7"><i class="fa fa-check"></i><b>9.2.2</b> Question 5</a></li>
<li class="chapter" data-level="9.2.3" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-6-7"><i class="fa fa-check"></i><b>9.2.3</b> Question 6</a></li>
<li class="chapter" data-level="9.2.4" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-7-7"><i class="fa fa-check"></i><b>9.2.4</b> Question 7</a></li>
<li class="chapter" data-level="9.2.5" data-path="support-vector-machines.html"><a href="support-vector-machines.html#question-8-7"><i class="fa fa-check"></i><b>9.2.5</b> Question 8</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="deep-learning.html"><a href="deep-learning.html"><i class="fa fa-check"></i><b>10</b> Deep Learning</a><ul>
<li class="chapter" data-level="10.1" data-path="deep-learning.html"><a href="deep-learning.html#conceptual-8"><i class="fa fa-check"></i><b>10.1</b> Conceptual</a><ul>
<li class="chapter" data-level="10.1.1" data-path="deep-learning.html"><a href="deep-learning.html#question-1-8"><i class="fa fa-check"></i><b>10.1.1</b> Question 1</a></li>
<li class="chapter" data-level="10.1.2" data-path="deep-learning.html"><a href="deep-learning.html#question-2-8"><i class="fa fa-check"></i><b>10.1.2</b> Question 2</a></li>
<li class="chapter" data-level="10.1.3" data-path="deep-learning.html"><a href="deep-learning.html#question-3-8"><i class="fa fa-check"></i><b>10.1.3</b> Question 3</a></li>
<li class="chapter" data-level="10.1.4" data-path="deep-learning.html"><a href="deep-learning.html#question-4-8"><i class="fa fa-check"></i><b>10.1.4</b> Question 4</a></li>
<li class="chapter" data-level="10.1.5" data-path="deep-learning.html"><a href="deep-learning.html#question-5-8"><i class="fa fa-check"></i><b>10.1.5</b> Question 5</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="deep-learning.html"><a href="deep-learning.html#applied-8"><i class="fa fa-check"></i><b>10.2</b> Applied</a><ul>
<li class="chapter" data-level="10.2.1" data-path="deep-learning.html"><a href="deep-learning.html#question-6-8"><i class="fa fa-check"></i><b>10.2.1</b> Question 6</a></li>
<li class="chapter" data-level="10.2.2" data-path="deep-learning.html"><a href="deep-learning.html#question-7-8"><i class="fa fa-check"></i><b>10.2.2</b> Question 7</a></li>
<li class="chapter" data-level="10.2.3" data-path="deep-learning.html"><a href="deep-learning.html#question-8-8"><i class="fa fa-check"></i><b>10.2.3</b> Question 8</a></li>
<li class="chapter" data-level="10.2.4" data-path="deep-learning.html"><a href="deep-learning.html#question-9-7"><i class="fa fa-check"></i><b>10.2.4</b> Question 9</a></li>
<li class="chapter" data-level="10.2.5" data-path="deep-learning.html"><a href="deep-learning.html#question-10-6"><i class="fa fa-check"></i><b>10.2.5</b> Question 10</a></li>
<li class="chapter" data-level="10.2.6" data-path="deep-learning.html"><a href="deep-learning.html#question-11-5"><i class="fa fa-check"></i><b>10.2.6</b> Question 11</a></li>
<li class="chapter" data-level="10.2.7" data-path="deep-learning.html"><a href="deep-learning.html#question-12-4"><i class="fa fa-check"></i><b>10.2.7</b> Question 12</a></li>
<li class="chapter" data-level="10.2.8" data-path="deep-learning.html"><a href="deep-learning.html#question-13-3"><i class="fa fa-check"></i><b>10.2.8</b> Question 13</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html"><i class="fa fa-check"></i><b>11</b> Survival Analysis and Censored Data</a><ul>
<li class="chapter" data-level="11.1" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#conceptual-9"><i class="fa fa-check"></i><b>11.1</b> Conceptual</a><ul>
<li class="chapter" data-level="11.1.1" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-1-9"><i class="fa fa-check"></i><b>11.1.1</b> Question 1</a></li>
<li class="chapter" data-level="11.1.2" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-2-9"><i class="fa fa-check"></i><b>11.1.2</b> Question 2</a></li>
<li class="chapter" data-level="11.1.3" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-3-9"><i class="fa fa-check"></i><b>11.1.3</b> Question 3</a></li>
<li class="chapter" data-level="11.1.4" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-4-9"><i class="fa fa-check"></i><b>11.1.4</b> Question 4</a></li>
<li class="chapter" data-level="11.1.5" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-5-9"><i class="fa fa-check"></i><b>11.1.5</b> Question 5</a></li>
<li class="chapter" data-level="11.1.6" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-6-9"><i class="fa fa-check"></i><b>11.1.6</b> Question 6</a></li>
<li class="chapter" data-level="11.1.7" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-7-9"><i class="fa fa-check"></i><b>11.1.7</b> Question 7</a></li>
<li class="chapter" data-level="11.1.8" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-8-9"><i class="fa fa-check"></i><b>11.1.8</b> Question 8</a></li>
<li class="chapter" data-level="11.1.9" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-9-8"><i class="fa fa-check"></i><b>11.1.9</b> Question 9</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#applied-9"><i class="fa fa-check"></i><b>11.2</b> Applied</a><ul>
<li class="chapter" data-level="11.2.1" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-10-7"><i class="fa fa-check"></i><b>11.2.1</b> Question 10</a></li>
<li class="chapter" data-level="11.2.2" data-path="survival-analysis-and-censored-data.html"><a href="survival-analysis-and-censored-data.html#question-11-6"><i class="fa fa-check"></i><b>11.2.2</b> Question 11</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html"><i class="fa fa-check"></i><b>12</b> Unsupervised Learning</a><ul>
<li class="chapter" data-level="12.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#conceptual-10"><i class="fa fa-check"></i><b>12.1</b> Conceptual</a><ul>
<li class="chapter" data-level="12.1.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-1-10"><i class="fa fa-check"></i><b>12.1.1</b> Question 1</a></li>
<li class="chapter" data-level="12.1.2" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-2-10"><i class="fa fa-check"></i><b>12.1.2</b> Question 2</a></li>
<li class="chapter" data-level="12.1.3" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-3-10"><i class="fa fa-check"></i><b>12.1.3</b> Question 3</a></li>
<li class="chapter" data-level="12.1.4" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-4-10"><i class="fa fa-check"></i><b>12.1.4</b> Question 4</a></li>
<li class="chapter" data-level="12.1.5" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-5-10"><i class="fa fa-check"></i><b>12.1.5</b> Question 5</a></li>
<li class="chapter" data-level="12.1.6" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-6-10"><i class="fa fa-check"></i><b>12.1.6</b> Question 6</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#applied-10"><i class="fa fa-check"></i><b>12.2</b> Applied</a><ul>
<li class="chapter" data-level="12.2.1" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-7-10"><i class="fa fa-check"></i><b>12.2.1</b> Question 7</a></li>
<li class="chapter" data-level="12.2.2" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-8-10"><i class="fa fa-check"></i><b>12.2.2</b> Question 8</a></li>
<li class="chapter" data-level="12.2.3" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-9-9"><i class="fa fa-check"></i><b>12.2.3</b> Question 9</a></li>
<li class="chapter" data-level="12.2.4" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-10-8"><i class="fa fa-check"></i><b>12.2.4</b> Question 10</a></li>
<li class="chapter" data-level="12.2.5" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-11-7"><i class="fa fa-check"></i><b>12.2.5</b> Question 11</a></li>
<li class="chapter" data-level="12.2.6" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-12-5"><i class="fa fa-check"></i><b>12.2.6</b> Question 12</a></li>
<li class="chapter" data-level="12.2.7" data-path="unsupervised-learning.html"><a href="unsupervised-learning.html#question-13-4"><i class="fa fa-check"></i><b>12.2.7</b> Question 13</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="multiple-testing.html"><a href="multiple-testing.html"><i class="fa fa-check"></i><b>13</b> Multiple Testing</a><ul>
<li class="chapter" data-level="13.1" data-path="multiple-testing.html"><a href="multiple-testing.html#conceptual-11"><i class="fa fa-check"></i><b>13.1</b> Conceptual</a><ul>
<li class="chapter" data-level="13.1.1" data-path="multiple-testing.html"><a href="multiple-testing.html#question-1-11"><i class="fa fa-check"></i><b>13.1.1</b> Question 1</a></li>
<li class="chapter" data-level="13.1.2" data-path="multiple-testing.html"><a href="multiple-testing.html#question-2-11"><i class="fa fa-check"></i><b>13.1.2</b> Question 2</a></li>
<li class="chapter" data-level="13.1.3" data-path="multiple-testing.html"><a href="multiple-testing.html#question-3-11"><i class="fa fa-check"></i><b>13.1.3</b> Question 3</a></li>
<li class="chapter" data-level="13.1.4" data-path="multiple-testing.html"><a href="multiple-testing.html#question-4-11"><i class="fa fa-check"></i><b>13.1.4</b> Question 4</a></li>
<li class="chapter" data-level="13.1.5" data-path="multiple-testing.html"><a href="multiple-testing.html#question-5-11"><i class="fa fa-check"></i><b>13.1.5</b> Question 5</a></li>
<li class="chapter" data-level="13.1.6" data-path="multiple-testing.html"><a href="multiple-testing.html#question-6-11"><i class="fa fa-check"></i><b>13.1.6</b> Question 6</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="multiple-testing.html"><a href="multiple-testing.html#applied-11"><i class="fa fa-check"></i><b>13.2</b> Applied</a><ul>
<li class="chapter" data-level="13.2.1" data-path="multiple-testing.html"><a href="multiple-testing.html#question-7-11"><i class="fa fa-check"></i><b>13.2.1</b> Question 7</a></li>
<li class="chapter" data-level="13.2.2" data-path="multiple-testing.html"><a href="multiple-testing.html#question-8-11"><i class="fa fa-check"></i><b>13.2.2</b> Question 8</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Introduction to Statistical Learning</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="resampling-methods" class="section level1 hasAnchor">
<h1><span class="header-section-number">5</span> Resampling Methods<a href="resampling-methods.html#resampling-methods" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="conceptual-3" class="section level2 hasAnchor">
<h2><span class="header-section-number">5.1</span> Conceptual<a href="resampling-methods.html#conceptual-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="question-1-3" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.1.1</span> Question 1<a href="resampling-methods.html#question-1-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Using basic statistical properties of the variance, as well as single-
variable calculus, derive (5.6). In other words, prove that <span class="math inline">\(\alpha\)</span> given by
(5.6) does indeed minimize <span class="math inline">\(Var(\alpha X + (1 − \alpha)Y)\)</span>.</p>
</blockquote>
<p>Equation 5.6 is:</p>
<p><span class="math display">\[
\alpha = \frac{\sigma^2_Y - \sigma_{XY}}{\sigma^2_X + \sigma^2_Y - 2\sigma_{XY}}
\]</span></p>
<p>Remember that:</p>
<p><span class="math display">\[
Var(aX) = a^2Var(X), \\ 
\mathrm{Var}(X + Y) = \mathrm{Var}(X) + \mathrm{Var}(Y) + \mathrm{Cov}(X,Y), \\
\mathrm{Cov}(aX, bY) = ab\mathrm{Cov}(X, Y)
\]</span></p>
<p>If we define <span class="math inline">\(\sigma^2_X = \mathrm{Var}(X)\)</span>, <span class="math inline">\(\sigma^2_Y = \mathrm{Var}(Y)\)</span> and
<span class="math inline">\(\sigma_{XY} = \mathrm{Cov}(X, Y)\)</span></p>
<p><span class="math display">\[\begin{align}
Var(\alpha X + (1 - \alpha)Y) 
  &amp;= \alpha^2\sigma^2_X + (1-\alpha)^2\sigma^2_Y + 2\alpha(1 - \alpha)\sigma_{XY} \\
  &amp;= \alpha^2\sigma^2_X + \sigma^2_Y - 2\alpha\sigma^2_Y + \alpha^2\sigma^2_Y + 
     2\alpha\sigma_{XY} - 2\alpha^2\sigma_{XY} 
\end{align}\]</span></p>
<p>Now we want to find when the rate of change of this function is 0 with respect
to <span class="math inline">\(\alpha\)</span>, so we compute the partial derivative, set to 0 and solve.</p>
<p><span class="math display">\[
\frac{\partial}{\partial{\alpha}} = 
  2\alpha\sigma^2_X - 2\sigma^2_Y + 2\alpha\sigma^2_Y + 2\sigma_{XY} - 4\alpha\sigma_{XY} = 0
\]</span></p>
<p>Moving <span class="math inline">\(\alpha\)</span> terms to the same side:</p>
<p><span class="math display">\[
\alpha\sigma^2_X + \alpha\sigma^2_Y - 2\alpha\sigma_{XY} = \sigma^2_Y - \sigma_{XY}
\]</span></p>
<p><span class="math display">\[
\alpha = \frac{\sigma^2_Y - \sigma_{XY}}{\sigma^2_X + \sigma^2_Y - 2\sigma_{XY}}
\]</span></p>
<p>We should also show that this is a minimum, so that the second partial
derivative wrt <span class="math inline">\(\alpha\)</span> is <span class="math inline">\(&gt;= 0\)</span>.</p>
<p><span class="math display">\[\begin{align}
\frac{\partial^2}{\partial{\alpha^2}} 
  &amp;=  2\sigma^2_X + 2\sigma^2_Y - 4\sigma_{XY} \\
  &amp;=  2(\sigma^2_X + \sigma^2_Y - 2\sigma_{XY}) \\
  &amp;= 2\mathrm{Var}(X - Y)
\end{align}\]</span></p>
<p>Since variance is positive, then this must be positive.</p>
</div>
<div id="question-2-3" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.1.2</span> Question 2<a href="resampling-methods.html#question-2-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>We will now derive the probability that a given observation is part of a
bootstrap sample. Suppose that we obtain a bootstrap sample from a set of n
observations.</p>
<ol style="list-style-type: lower-alpha">
<li>What is the probability that the first bootstrap observation is <em>not</em> the
<span class="math inline">\(j\)</span>th observation from the original sample? Justify your answer.</li>
</ol>
</blockquote>
<p>This is 1 - probability that it is the <span class="math inline">\(j\)</span>th = <span class="math inline">\(1 - 1/n\)</span>.</p>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>What is the probability that the second bootstrap observation is <em>not</em> the
<span class="math inline">\(j\)</span>th observation from the original sample?</li>
</ol>
</blockquote>
<p>Since each bootstrap observation is a random sample, this probability is the
same (<span class="math inline">\(1 - 1/n\)</span>).</p>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Argue that the probability that the <span class="math inline">\(j\)</span>th observation is <em>not</em> in the
bootstrap sample is <span class="math inline">\((1 − 1/n)^n\)</span>.</li>
</ol>
</blockquote>
<p>For the <span class="math inline">\(j\)</span>th observation to not be in the sample, it would have to <em>not</em> be
picked for each of <span class="math inline">\(n\)</span> positions, so not picked for <span class="math inline">\(1, 2, ..., n\)</span>, thus
the probability is <span class="math inline">\((1 - 1/n)^n\)</span></p>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>When <span class="math inline">\(n = 5\)</span>, what is the probability that the <span class="math inline">\(j\)</span>th observation is in the
bootstrap sample?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="resampling-methods.html#cb277-1"></a>n &lt;-<span class="st"> </span><span class="dv">5</span></span>
<span id="cb277-2"><a href="resampling-methods.html#cb277-2"></a><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span><span class="op">/</span>n)<span class="op">^</span>n</span></code></pre></div>
<pre><code>## [1] 0.67232</code></pre>
<p><span class="math inline">\(p = 0.67\)</span></p>
<blockquote>
<ol start="5" style="list-style-type: lower-alpha">
<li>When <span class="math inline">\(n = 100\)</span>, what is the probability that the <span class="math inline">\(j\)</span>th observation is in
the bootstrap sample?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="resampling-methods.html#cb279-1"></a>n &lt;-<span class="st"> </span><span class="dv">100</span></span>
<span id="cb279-2"><a href="resampling-methods.html#cb279-2"></a><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span><span class="op">/</span>n)<span class="op">^</span>n</span></code></pre></div>
<pre><code>## [1] 0.6339677</code></pre>
<p><span class="math inline">\(p = 0.64\)</span></p>
<blockquote>
<ol start="6" style="list-style-type: lower-alpha">
<li>When <span class="math inline">\(n = 10,000\)</span>, what is the probability that the <span class="math inline">\(j\)</span>th observation is
in the bootstrap sample?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="resampling-methods.html#cb281-1"></a>n &lt;-<span class="st"> </span><span class="dv">100000</span></span>
<span id="cb281-2"><a href="resampling-methods.html#cb281-2"></a><span class="dv">1</span> <span class="op">-</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span><span class="op">/</span>n)<span class="op">^</span>n</span></code></pre></div>
<pre><code>## [1] 0.6321224</code></pre>
<p><span class="math inline">\(p = 0.63\)</span></p>
<blockquote>
<ol start="7" style="list-style-type: lower-alpha">
<li>Create a plot that displays, for each integer value of <span class="math inline">\(n\)</span> from 1 to
100,000, the probability that the <span class="math inline">\(j\)</span>th observation is in the bootstrap
sample. Comment on what you observe.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="resampling-methods.html#cb283-1"></a>x &lt;-<span class="st"> </span><span class="kw">sapply</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">100000</span>, <span class="cf">function</span>(n) <span class="dv">1</span> <span class="op">-</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span><span class="op">/</span>n)<span class="op">^</span>n)</span>
<span id="cb283-2"><a href="resampling-methods.html#cb283-2"></a><span class="kw">plot</span>(x, <span class="dt">log =</span> <span class="st">&quot;x&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;o&quot;</span>)</span></code></pre></div>
<p><img src="05-resampling-methods_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>The probability rapidly approaches 0.63 with increasing <span class="math inline">\(n\)</span>.</p>
<p>Note that <span class="math display">\[e^x = \lim_{x \to \inf} \left(1 + \frac{x}{n}\right)^n,\]</span> so with <span class="math inline">\(x = -1\)</span>, we
can see that our limit is <span class="math inline">\(1 - e^{-1} = 1 - 1/e\)</span>.</p>
<blockquote>
<ol start="8" style="list-style-type: lower-alpha">
<li><p>We will now investigate numerically the probability that a bootstrap
sample of size <span class="math inline">\(n = 100\)</span> contains the <span class="math inline">\(j\)</span>th observation. Here <span class="math inline">\(j = 4\)</span>. We
repeatedly create bootstrap samples, and each time we record whether or not
the fourth observation is contained in the bootstrap sample.</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="resampling-methods.html#cb284-1"></a><span class="op">&gt;</span><span class="st"> </span>store &lt;-<span class="st"> </span><span class="kw">rep</span> (<span class="ot">NA</span>, <span class="dv">10000</span>)</span>
<span id="cb284-2"><a href="resampling-methods.html#cb284-2"></a><span class="op">&gt;</span><span class="st"> </span><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10000</span>) {</span>
<span id="cb284-3"><a href="resampling-methods.html#cb284-3"></a>    store[i] &lt;-<span class="st"> </span><span class="kw">sum</span>(<span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">100</span>, <span class="dt">rep =</span> <span class="ot">TRUE</span>) <span class="op">==</span><span class="st"> </span><span class="dv">4</span>) <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span></span>
<span id="cb284-4"><a href="resampling-methods.html#cb284-4"></a>}</span>
<span id="cb284-5"><a href="resampling-methods.html#cb284-5"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">mean</span>(store)</span></code></pre></div>
<p>Comment on the results obtained.</p></li>
</ol>
</blockquote>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="resampling-methods.html#cb285-1"></a>store &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">10000</span>, <span class="kw">sum</span>(<span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">100</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>) <span class="op">==</span><span class="st"> </span><span class="dv">4</span>) <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>)</span>
<span id="cb285-2"><a href="resampling-methods.html#cb285-2"></a><span class="kw">mean</span>(store)</span></code></pre></div>
<pre><code>## [1] 0.6317</code></pre>
<p>The probability of including <span class="math inline">\(4\)</span> when resampling numbers <span class="math inline">\(1...100\)</span> is close to
<span class="math inline">\(1 - (1 - 1/100)^{100}\)</span>.</p>
</div>
<div id="question-3-3" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.1.3</span> Question 3<a href="resampling-methods.html#question-3-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<ol start="3" style="list-style-type: decimal">
<li>We now review <span class="math inline">\(k\)</span>-fold cross-validation.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Explain how <span class="math inline">\(k\)</span>-fold cross-validation is implemented.</li>
</ol>
</blockquote>
<p>We divided our data into (approximately equal) <span class="math inline">\(k\)</span> subsets, and then generate
predictions for each <span class="math inline">\(k\)</span>th set, training on the exclusive <span class="math inline">\(k\)</span> sets combined.</p>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>What are the advantages and disadvantages of <span class="math inline">\(k\)</span>-fold cross-validation
relative to:
<ol style="list-style-type: lower-roman">
<li>The validation set approach?</li>
<li>LOOCV?</li>
</ol></li>
</ol>
</blockquote>
<p>When using a validation set, we can only train on a small portion of the data
as we must reserve the rest for validation. As a result it can overestimate the
test error rate (assuming we then train using the complete data for future
prediction). It is also sensitive to which observations are including in train
vs. test. It is, however, low cost in terms of processing time (as we only
have to fit one model).</p>
<p>When using LOOCV, we can train on <span class="math inline">\(n-1\)</span> observations, however, the trained
models we generate each differ only by the inclusion (and exclusion) of a
single observation. As a result, LOOCV can have high variance (the models fit
will be similar, and might be quite different to what we would obtain with a
different data set). LOOCV is also costly in terms of processing time.</p>
</div>
<div id="question-4-3" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.1.4</span> Question 4<a href="resampling-methods.html#question-4-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>Suppose that we use some statistical learning method to make a prediction for
the response <span class="math inline">\(Y\)</span> for a particular value of the predictor <span class="math inline">\(X\)</span>. Carefully
describe how we might estimate the standard deviation of our prediction.</p>
</blockquote>
<p>We could address this with bootstrapping. Our procedure would be to (jointly)
resample <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> variables and fit our model many times. For each model we
could obtain a summary of our prediction and calculate the standard deviation
over bootstrapped samples.</p>
</div>
</div>
<div id="applied-3" class="section level2 hasAnchor">
<h2><span class="header-section-number">5.2</span> Applied<a href="resampling-methods.html#applied-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="question-5-3" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.2.1</span> Question 5<a href="resampling-methods.html#question-5-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>In Chapter 4, we used logistic regression to predict the probability of
<code>default</code> using <code>income</code> and <code>balance</code> on the <code>Default</code> data set. We will now
estimate the test error of this logistic regression model using the
validation set approach. Do not forget to set a random seed before beginning
your analysis.</p>
<ol style="list-style-type: lower-alpha">
<li>Fit a logistic regression model that uses <code>income</code> and <code>balance</code> to predict
<code>default</code>.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="resampling-methods.html#cb287-1"></a><span class="kw">library</span>(ISLR2)</span>
<span id="cb287-2"><a href="resampling-methods.html#cb287-2"></a><span class="kw">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb287-3"><a href="resampling-methods.html#cb287-3"></a>fit &lt;-<span class="st"> </span><span class="kw">glm</span>(default <span class="op">~</span><span class="st"> </span>income <span class="op">+</span><span class="st"> </span>balance, <span class="dt">data =</span> Default, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</span></code></pre></div>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Using the validation set approach, estimate the test error of this model.
In order to do this, you must perform the following steps:
<ol style="list-style-type: lower-roman">
<li>Split the sample set into a training set and a validation set.</li>
<li>Fit a multiple logistic regression model using only the training
observations.</li>
<li>Obtain a prediction of default status for each individual in
the validation set by computing the posterior probability of
default for that individual, and classifying the individual to
the <code>default</code> category if the posterior probability is greater
than 0.5.</li>
<li>Compute the validation set error, which is the fraction of
the observations in the validation set that are misclassified.</li>
</ol></li>
</ol>
</blockquote>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="resampling-methods.html#cb288-1"></a>train &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">nrow</span>(Default), <span class="kw">nrow</span>(Default) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>)</span>
<span id="cb288-2"><a href="resampling-methods.html#cb288-2"></a>fit &lt;-<span class="st"> </span><span class="kw">glm</span>(default <span class="op">~</span><span class="st"> </span>income <span class="op">+</span><span class="st"> </span>balance, <span class="dt">data =</span> Default, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="dt">subset =</span> train)</span>
<span id="cb288-3"><a href="resampling-methods.html#cb288-3"></a>pred &lt;-<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">predict</span>(fit, <span class="dt">newdata =</span> Default[<span class="op">-</span>train, ], <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>) <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.5</span>, <span class="st">&quot;Yes&quot;</span>, <span class="st">&quot;No&quot;</span>)</span>
<span id="cb288-4"><a href="resampling-methods.html#cb288-4"></a><span class="kw">table</span>(pred, Default<span class="op">$</span>default[<span class="op">-</span>train]) </span></code></pre></div>
<pre><code>##      
## pred    No  Yes
##   No  4817  110
##   Yes   20   53</code></pre>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="resampling-methods.html#cb290-1"></a><span class="kw">mean</span>(pred <span class="op">!=</span><span class="st"> </span>Default<span class="op">$</span>default[<span class="op">-</span>train])</span></code></pre></div>
<pre><code>## [1] 0.026</code></pre>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Repeat the process in (b) three times, using three different splits of the
observations into a training set and a validation set. Comment on the
results obtained.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb292-1"><a href="resampling-methods.html#cb292-1"></a><span class="kw">replicate</span>(<span class="dv">3</span>, {</span>
<span id="cb292-2"><a href="resampling-methods.html#cb292-2"></a>  train &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">nrow</span>(Default), <span class="kw">nrow</span>(Default) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>)</span>
<span id="cb292-3"><a href="resampling-methods.html#cb292-3"></a>  fit &lt;-<span class="st"> </span><span class="kw">glm</span>(default <span class="op">~</span><span class="st"> </span>income <span class="op">+</span><span class="st"> </span>balance, <span class="dt">data =</span> Default, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="dt">subset =</span> train)</span>
<span id="cb292-4"><a href="resampling-methods.html#cb292-4"></a>  pred &lt;-<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">predict</span>(fit, <span class="dt">newdata =</span> Default[<span class="op">-</span>train, ], <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>) <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.5</span>, <span class="st">&quot;Yes&quot;</span>, <span class="st">&quot;No&quot;</span>)</span>
<span id="cb292-5"><a href="resampling-methods.html#cb292-5"></a>  <span class="kw">mean</span>(pred <span class="op">!=</span><span class="st"> </span>Default<span class="op">$</span>default[<span class="op">-</span>train])</span>
<span id="cb292-6"><a href="resampling-methods.html#cb292-6"></a>})</span></code></pre></div>
<pre><code>## [1] 0.0260 0.0294 0.0258</code></pre>
<p>The results obtained are variable and depend on the samples allocated to
training vs. test.</p>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Now consider a logistic regression model that predicts the probability of
<code>default</code> using <code>income</code>, <code>balance</code>, and a dummy variable for <code>student</code>.
Estimate the test error for this model using the validation set approach.
Comment on whether or not including a dummy variable for <code>student</code> leads to
a reduction in the test error rate.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb294-1"><a href="resampling-methods.html#cb294-1"></a><span class="kw">replicate</span>(<span class="dv">3</span>, {</span>
<span id="cb294-2"><a href="resampling-methods.html#cb294-2"></a>  train &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="kw">nrow</span>(Default), <span class="kw">nrow</span>(Default) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>)</span>
<span id="cb294-3"><a href="resampling-methods.html#cb294-3"></a>  fit &lt;-<span class="st"> </span><span class="kw">glm</span>(default <span class="op">~</span><span class="st"> </span>income <span class="op">+</span><span class="st"> </span>balance <span class="op">+</span><span class="st"> </span>student, <span class="dt">data =</span> Default, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>, <span class="dt">subset =</span> train)</span>
<span id="cb294-4"><a href="resampling-methods.html#cb294-4"></a>  pred &lt;-<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">predict</span>(fit, <span class="dt">newdata =</span> Default[<span class="op">-</span>train, ], <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>) <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.5</span>, <span class="st">&quot;Yes&quot;</span>, <span class="st">&quot;No&quot;</span>)</span>
<span id="cb294-5"><a href="resampling-methods.html#cb294-5"></a>  <span class="kw">mean</span>(pred <span class="op">!=</span><span class="st"> </span>Default<span class="op">$</span>default[<span class="op">-</span>train])</span>
<span id="cb294-6"><a href="resampling-methods.html#cb294-6"></a>})</span></code></pre></div>
<pre><code>## [1] 0.0278 0.0256 0.0250</code></pre>
<p>Including <code>student</code> does not seem to make a substantial improvement to the
test error.</p>
</div>
<div id="question-6-3" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.2.2</span> Question 6<a href="resampling-methods.html#question-6-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>We continue to consider the use of a logistic regression model to predict the
probability of <code>default</code> using <code>income</code> and <code>balance</code> on the <code>Default</code> data
set. In particular, we will now compute estimates for the standard errors of
the <code>income</code> and <code>balance</code> logistic regression coefficients in two different
ways: (1) using the bootstrap, and (2) using the standard formula for
computing the standard errors in the <code>glm()</code> function. Do not forget to set a
random seed before beginning your analysis.</p>
<ol style="list-style-type: lower-alpha">
<li>Using the <code>summary()</code> and <code>glm()</code> functions, determine the estimated
standard errors for the coefficients associated with <code>income</code> and
<code>balance</code> in a multiple logistic regression model that uses both
predictors.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb296-1"><a href="resampling-methods.html#cb296-1"></a>fit &lt;-<span class="st"> </span><span class="kw">glm</span>(default <span class="op">~</span><span class="st"> </span>income <span class="op">+</span><span class="st"> </span>balance, <span class="dt">data =</span> Default, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</span>
<span id="cb296-2"><a href="resampling-methods.html#cb296-2"></a><span class="kw">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = default ~ income + balance, family = &quot;binomial&quot;, 
##     data = Default)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.4725  -0.1444  -0.0574  -0.0211   3.7245  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.154e+01  4.348e-01 -26.545  &lt; 2e-16 ***
## income       2.081e-05  4.985e-06   4.174 2.99e-05 ***
## balance      5.647e-03  2.274e-04  24.836  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 2920.6  on 9999  degrees of freedom
## Residual deviance: 1579.0  on 9997  degrees of freedom
## AIC: 1585
## 
## Number of Fisher Scoring iterations: 8</code></pre>
<p>The standard errors obtained by bootstrapping are <span class="math inline">\(\beta_1\)</span> = 5.0e-6 and
<span class="math inline">\(\beta_2\)</span> = 2.3e-4.</p>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Write a function, <code>boot.fn()</code>, that takes as input the <code>Default</code> data set
as well as an index of the observations, and that outputs the coefficient
estimates for <code>income</code> and <code>balance</code> in the multiple logistic regression
model.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb298-1"><a href="resampling-methods.html#cb298-1"></a>boot.fn &lt;-<span class="st"> </span><span class="cf">function</span>(x, i) {</span>
<span id="cb298-2"><a href="resampling-methods.html#cb298-2"></a>  fit &lt;-<span class="st"> </span><span class="kw">glm</span>(default <span class="op">~</span><span class="st"> </span>income <span class="op">+</span><span class="st"> </span>balance, <span class="dt">data =</span> Default[i, ], <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</span>
<span id="cb298-3"><a href="resampling-methods.html#cb298-3"></a>  <span class="kw">coef</span>(fit)[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb298-4"><a href="resampling-methods.html#cb298-4"></a>}</span></code></pre></div>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Use the <code>boot()</code> function together with your <code>boot.fn()</code> function to
estimate the standard errors of the logistic regression coefficients for
income and balance.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="resampling-methods.html#cb299-1"></a><span class="kw">library</span>(boot)</span>
<span id="cb299-2"><a href="resampling-methods.html#cb299-2"></a><span class="kw">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb299-3"><a href="resampling-methods.html#cb299-3"></a><span class="kw">boot</span>(Default, boot.fn, <span class="dt">R =</span> <span class="dv">1000</span>)</span></code></pre></div>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = Default, statistic = boot.fn, R = 1000)
## 
## 
## Bootstrap Statistics :
##         original       bias     std. error
## t1* 2.080898e-05 2.737444e-08 5.073444e-06
## t2* 5.647103e-03 1.176249e-05 2.299133e-04</code></pre>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Comment on the estimated standard errors obtained using the <code>glm()</code>
function and using your bootstrap function.</li>
</ol>
</blockquote>
<p>The standard errors obtained by bootstrapping are similar to those estimated
by <code>glm</code>.</p>
</div>
<div id="question-7-3" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.2.3</span> Question 7<a href="resampling-methods.html#question-7-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>In Sections 5.3.2 and 5.3.3, we saw that the <code>cv.glm()</code> function can be used
in order to compute the LOOCV test error estimate. Alternatively, one could
compute those quantities using just the <code>glm()</code> and <code>predict.glm()</code>
functions, and a for loop. You will now take this approach in order to
compute the LOOCV error for a simple logistic regression model on the <code>Weekly</code>
data set. Recall that in the context of classification problems, the LOOCV
error is given in (5.4).</p>
<ol style="list-style-type: lower-alpha">
<li>Fit a logistic regression model that predicts <code>Direction</code> using <code>Lag1</code> and
<code>Lag2</code>.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="resampling-methods.html#cb301-1"></a>fit &lt;-<span class="st"> </span><span class="kw">glm</span>(Direction <span class="op">~</span><span class="st"> </span>Lag1 <span class="op">+</span><span class="st"> </span>Lag2, <span class="dt">data =</span> Weekly, <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</span></code></pre></div>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Fit a logistic regression model that predicts <code>Direction</code> using <code>Lag1</code> and
<code>Lag2</code> <em>using all but the first observation</em>.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="resampling-methods.html#cb302-1"></a>fit &lt;-<span class="st"> </span><span class="kw">glm</span>(Direction <span class="op">~</span><span class="st"> </span>Lag1 <span class="op">+</span><span class="st"> </span>Lag2, <span class="dt">data =</span> Weekly[<span class="op">-</span><span class="dv">1</span>, ], <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</span></code></pre></div>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Use the model from (b) to predict the direction of the first
observation. You can do this by predicting that the first observation will
go up if <span class="math inline">\(P(\)</span><code>Direction="Up" | Lag1 , Lag2</code><span class="math inline">\() &gt; 0.5\)</span>. Was this observation
correctly classified?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="resampling-methods.html#cb303-1"></a><span class="kw">predict</span>(fit, <span class="dt">newdata =</span> Weekly[<span class="dv">1</span>, , <span class="dt">drop =</span> <span class="ot">FALSE</span>], <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>) <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.5</span></span></code></pre></div>
<pre><code>##    1 
## TRUE</code></pre>
<p>Yes the observation was correctly classified.</p>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Write a for loop from <span class="math inline">\(i = 1\)</span> to <span class="math inline">\(i = n\)</span>, where <span class="math inline">\(n\)</span> is the number of
observations in the data set, that performs each of the following steps:
<ol style="list-style-type: lower-roman">
<li>Fit a logistic regression model using all but the <span class="math inline">\(i\)</span>th observation
to predict <code>Direction</code> using <code>Lag1</code> and <code>Lag2</code> .</li>
<li>Compute the posterior probability of the market moving up
for the <span class="math inline">\(i\)</span>th observation.</li>
<li>Use the posterior probability for the <span class="math inline">\(i\)</span>th observation in order
to predict whether or not the market moves up.</li>
<li>Determine whether or not an error was made in predicting the
direction for the <span class="math inline">\(i\)</span>th observation. If an error was made, then
indicate this as a 1, and otherwise indicate it as a 0.</li>
</ol></li>
</ol>
</blockquote>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="resampling-methods.html#cb305-1"></a>error &lt;-<span class="st"> </span><span class="kw">numeric</span>(<span class="kw">nrow</span>(Weekly))</span>
<span id="cb305-2"><a href="resampling-methods.html#cb305-2"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(Weekly)) {</span>
<span id="cb305-3"><a href="resampling-methods.html#cb305-3"></a>  fit &lt;-<span class="st"> </span><span class="kw">glm</span>(Direction <span class="op">~</span><span class="st"> </span>Lag1 <span class="op">+</span><span class="st"> </span>Lag2, <span class="dt">data =</span> Weekly[<span class="op">-</span>i, ], <span class="dt">family =</span> <span class="st">&quot;binomial&quot;</span>)</span>
<span id="cb305-4"><a href="resampling-methods.html#cb305-4"></a>  p &lt;-<span class="st"> </span><span class="kw">predict</span>(fit, <span class="dt">newdata =</span> Weekly[i, , <span class="dt">drop =</span> <span class="ot">FALSE</span>], <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>) <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.5</span></span>
<span id="cb305-5"><a href="resampling-methods.html#cb305-5"></a>  error[i] &lt;-<span class="st"> </span><span class="kw">ifelse</span>(p, <span class="st">&quot;Down&quot;</span>, <span class="st">&quot;Up&quot;</span>) <span class="op">==</span><span class="st"> </span>Weekly<span class="op">$</span>Direction[i]</span>
<span id="cb305-6"><a href="resampling-methods.html#cb305-6"></a>}</span></code></pre></div>
<blockquote>
<ol start="5" style="list-style-type: lower-alpha">
<li>Take the average of the <span class="math inline">\(n\)</span> numbers obtained in (d) in order to obtain the
LOOCV estimate for the test error. Comment on the results.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="resampling-methods.html#cb306-1"></a><span class="kw">mean</span>(error)</span></code></pre></div>
<pre><code>## [1] 0.4499541</code></pre>
<p>The LOOCV test error rate is 45% which implies that our predictions are
marginally more often correct than not.</p>
</div>
<div id="question-8-3" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.2.4</span> Question 8<a href="resampling-methods.html#question-8-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>We will now perform cross-validation on a simulated data set.</p>
<ol style="list-style-type: lower-alpha">
<li><p>Generate a simulated data set as follows:</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="resampling-methods.html#cb308-1"></a><span class="op">&gt;</span><span class="st"> </span><span class="kw">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb308-2"><a href="resampling-methods.html#cb308-2"></a><span class="op">&gt;</span><span class="st"> </span>x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb308-3"><a href="resampling-methods.html#cb308-3"></a><span class="op">&gt;</span><span class="st"> </span>y &lt;-<span class="st"> </span>x <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span>x<span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span></code></pre></div>
<p>In this data set, what is <span class="math inline">\(n\)</span> and what is <span class="math inline">\(p\)</span>? Write out the model
used to generate the data in equation form.</p></li>
</ol>
</blockquote>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="resampling-methods.html#cb309-1"></a><span class="kw">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb309-2"><a href="resampling-methods.html#cb309-2"></a>x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb309-3"><a href="resampling-methods.html#cb309-3"></a>y &lt;-<span class="st"> </span>x <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>x<span class="op">^</span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>)</span></code></pre></div>
<p><span class="math inline">\(n\)</span> is 100 and <span class="math inline">\(p\)</span> is 1 (there are 100 observations and <span class="math inline">\(y\)</span> is predicted with
a single variable <span class="math inline">\(x\)</span>). The model equation is: <span class="math display">\[y = -2x^2 + x + \epsilon\]</span>.</p>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Create a scatterplot of <span class="math inline">\(X\)</span> against <span class="math inline">\(Y\)</span>. Comment on what you find.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="resampling-methods.html#cb310-1"></a><span class="kw">plot</span>(x, y)</span></code></pre></div>
<p><img src="05-resampling-methods_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p><span class="math inline">\(y\)</span> has a (negative) quadratic relationship with <span class="math inline">\(x\)</span>.</p>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Set a random seed, and then compute the LOOCV errors that result from
fitting the following four models using least squares:
<ol style="list-style-type: lower-roman">
<li><span class="math inline">\(Y = \beta_0 + \beta_1 X + \epsilon\)</span></li>
<li><span class="math inline">\(Y = \beta_0 + \beta_1 X + \beta_2 X^2 + \epsilon\)</span></li>
<li><span class="math inline">\(Y = \beta_0 + \beta_1 X + \beta_2 X^2 + \beta_3 X^3 + \epsilon\)</span></li>
<li><span class="math inline">\(Y = \beta_0 + \beta_1 X + \beta_2 X^2 + \beta_3 X^3 + \beta_4 X^4 + \epsilon\)</span>.</li>
</ol>
Note you may find it helpful to use the <code>data.frame()</code> function
to create a single data set containing both <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="resampling-methods.html#cb311-1"></a><span class="kw">library</span>(boot)</span>
<span id="cb311-2"><a href="resampling-methods.html#cb311-2"></a><span class="kw">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb311-3"><a href="resampling-methods.html#cb311-3"></a>dat &lt;-<span class="st"> </span><span class="kw">data.frame</span>(x, y)</span>
<span id="cb311-4"><a href="resampling-methods.html#cb311-4"></a><span class="kw">sapply</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="cf">function</span>(i) <span class="kw">cv.glm</span>(dat, <span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(x, i)))<span class="op">$</span>delta[<span class="dv">1</span>])</span></code></pre></div>
<pre><code>## [1] 7.2881616 0.9374236 0.9566218 0.9539049</code></pre>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Repeat (c) using another random seed, and report your results.
Are your results the same as what you got in (c)? Why?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="resampling-methods.html#cb313-1"></a><span class="kw">set.seed</span>(<span class="dv">43</span>)</span>
<span id="cb313-2"><a href="resampling-methods.html#cb313-2"></a>dat &lt;-<span class="st"> </span><span class="kw">data.frame</span>(x, y)</span>
<span id="cb313-3"><a href="resampling-methods.html#cb313-3"></a><span class="kw">sapply</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="cf">function</span>(i) <span class="kw">cv.glm</span>(dat, <span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(x, i)))<span class="op">$</span>delta[<span class="dv">1</span>])</span></code></pre></div>
<pre><code>## [1] 7.2881616 0.9374236 0.9566218 0.9539049</code></pre>
<p>The results are the same because we are using LOOCV. When doing this, the model
is fit leaving each one of the observations out in turn, and thus there is no
stochasticity involved.</p>
<blockquote>
<ol start="5" style="list-style-type: lower-alpha">
<li>Which of the models in (c) had the smallest LOOCV error? Is this what you
expected? Explain your answer.</li>
</ol>
</blockquote>
<p>The second model had the smallest LOOCV. This what would be expected since the
model to generate the data was quadratic and we are measuring the test (rather
than training) error rate to evaluate performance.</p>
<blockquote>
<ol start="6" style="list-style-type: lower-alpha">
<li>Comment on the statistical significance of the coefficient estimates
that results from fitting each of the models in (c) using least squares.
Do these results agree with the conclusions drawn based on the
cross-validation results?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="resampling-methods.html#cb315-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>) <span class="kw">printCoefmat</span>(<span class="kw">coef</span>(<span class="kw">summary</span>(<span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(x, i), <span class="dt">data =</span> dat))))</span></code></pre></div>
<pre><code>##             Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept) -1.55002    0.26001 -5.9613 3.954e-08 ***
## poly(x, i)   6.18883    2.60014  2.3802   0.01924 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##               Estimate Std. Error  t value  Pr(&gt;|t|)    
## (Intercept)  -1.550023   0.095803 -16.1792 &lt; 2.2e-16 ***
## poly(x, i)1   6.188826   0.958032   6.4599 4.185e-09 ***
## poly(x, i)2 -23.948305   0.958032 -24.9974 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##               Estimate Std. Error  t value  Pr(&gt;|t|)    
## (Intercept)  -1.550023   0.096263 -16.1019 &lt; 2.2e-16 ***
## poly(x, i)1   6.188826   0.962632   6.4291 4.972e-09 ***
## poly(x, i)2 -23.948305   0.962632 -24.8779 &lt; 2.2e-16 ***
## poly(x, i)3   0.264106   0.962632   0.2744    0.7844    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
##               Estimate Std. Error  t value  Pr(&gt;|t|)    
## (Intercept)  -1.550023   0.095905 -16.1620 &lt; 2.2e-16 ***
## poly(x, i)1   6.188826   0.959051   6.4531 4.591e-09 ***
## poly(x, i)2 -23.948305   0.959051 -24.9708 &lt; 2.2e-16 ***
## poly(x, i)3   0.264106   0.959051   0.2754    0.7836    
## poly(x, i)4   1.257095   0.959051   1.3108    0.1931    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can see that the coefficients in the first model are not highly significant,
but all terms (<span class="math inline">\(\beta_0, \beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>) are in the quadratic model.
After this, subsequent <span class="math inline">\(\beta_n\)</span> terms are not significant. Therefore, these
results agree with those from cross-validation.</p>
</div>
<div id="question-9-3" class="section level3 hasAnchor">
<h3><span class="header-section-number">5.2.5</span> Question 9<a href="resampling-methods.html#question-9-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<blockquote>
<p>We will now consider the <code>Boston</code> housing data set, from the <code>ISLR2</code>
library.</p>
<ol style="list-style-type: lower-alpha">
<li>Based on this data set, provide an estimate for the population mean of
<code>medv</code>. Call this estimate <span class="math inline">\(\hat\mu\)</span>.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="resampling-methods.html#cb317-1"></a>(mu &lt;-<span class="st"> </span><span class="kw">mean</span>(Boston<span class="op">$</span>medv))</span></code></pre></div>
<pre><code>## [1] 22.53281</code></pre>
<blockquote>
<ol start="2" style="list-style-type: lower-alpha">
<li>Provide an estimate of the standard error of <span class="math inline">\(\hat\mu\)</span>. Interpret this
result.</li>
</ol>
<p><em>Hint: We can compute the standard error of the sample mean by
dividing the sample standard deviation by the square root of the number of
observations.</em></p>
</blockquote>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="resampling-methods.html#cb319-1"></a><span class="kw">sd</span>(Boston<span class="op">$</span>medv) <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="kw">length</span>(Boston<span class="op">$</span>medv))</span></code></pre></div>
<pre><code>## [1] 0.4088611</code></pre>
<blockquote>
<ol start="3" style="list-style-type: lower-alpha">
<li>Now estimate the standard error of <span class="math inline">\(\hat\mu\)</span> using the bootstrap. How does
this compare to your answer from (b)?</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="resampling-methods.html#cb321-1"></a><span class="kw">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb321-2"><a href="resampling-methods.html#cb321-2"></a>(bs &lt;-<span class="st"> </span><span class="kw">boot</span>(Boston<span class="op">$</span>medv, <span class="cf">function</span>(v, i) <span class="kw">mean</span>(v[i]), <span class="dv">10000</span>))</span></code></pre></div>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = Boston$medv, statistic = function(v, i) mean(v[i]), 
##     R = 10000)
## 
## 
## Bootstrap Statistics :
##     original      bias    std. error
## t1* 22.53281 0.002175751   0.4029139</code></pre>
<p>The standard error using the bootstrap (0.403) is very close to that
obtained from the formula above (0.409).</p>
<blockquote>
<ol start="4" style="list-style-type: lower-alpha">
<li>Based on your bootstrap estimate from (c), provide a 95% confidence
interval for the mean of <code>medv</code>. Compare it to the results obtained using
<code>t.test(Boston$medv)</code>.</li>
</ol>
<p><em>Hint: You can approximate a 95% confidence interval using the
formula <span class="math inline">\([\hat\mu − 2SE(\hat\mu), \hat\mu + 2SE(\hat\mu)].\)</span></em></p>
</blockquote>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="resampling-methods.html#cb323-1"></a>se &lt;-<span class="st"> </span><span class="kw">sd</span>(bs<span class="op">$</span>t)</span>
<span id="cb323-2"><a href="resampling-methods.html#cb323-2"></a><span class="kw">c</span>(mu <span class="op">-</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span>se, mu <span class="op">+</span><span class="st"> </span><span class="dv">2</span><span class="op">*</span>se)</span></code></pre></div>
<pre><code>## [1] 21.72698 23.33863</code></pre>
<blockquote>
<ol start="5" style="list-style-type: lower-alpha">
<li>Based on this data set, provide an estimate, <span class="math inline">\(\hat\mu_{med}\)</span>, for the
median value of <code>medv</code> in the population.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="resampling-methods.html#cb325-1"></a><span class="kw">median</span>(Boston<span class="op">$</span>medv)</span></code></pre></div>
<pre><code>## [1] 21.2</code></pre>
<blockquote>
<ol start="6" style="list-style-type: lower-alpha">
<li>We now would like to estimate the standard error of <span class="math inline">\(\hat\mu_{med}\)</span>.
Unfortunately, there is no simple formula for computing the standard error
of the median. Instead, estimate the standard error of the median using
the bootstrap. Comment on your findings.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="resampling-methods.html#cb327-1"></a><span class="kw">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb327-2"><a href="resampling-methods.html#cb327-2"></a><span class="kw">boot</span>(Boston<span class="op">$</span>medv, <span class="cf">function</span>(v, i) <span class="kw">median</span>(v[i]), <span class="dv">10000</span>)</span></code></pre></div>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = Boston$medv, statistic = function(v, i) median(v[i]), 
##     R = 10000)
## 
## 
## Bootstrap Statistics :
##     original   bias    std. error
## t1*     21.2 -0.01331   0.3744634</code></pre>
<p>The estimated standard error of the median is 0.374. This is lower than the
standard error of the mean.</p>
<blockquote>
<ol start="7" style="list-style-type: lower-alpha">
<li>Based on this data set, provide an estimate for the tenth percentile of
<code>medv</code> in Boston census tracts. Call this quantity <span class="math inline">\(\hat\mu_{0.1}\)</span>. (You
can use the <code>quantile()</code> function.)</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="resampling-methods.html#cb329-1"></a><span class="kw">quantile</span>(Boston<span class="op">$</span>medv, <span class="fl">0.1</span>)</span></code></pre></div>
<pre><code>##   10% 
## 12.75</code></pre>
<blockquote>
<ol start="8" style="list-style-type: lower-alpha">
<li>Use the bootstrap to estimate the standard error of <span class="math inline">\(\hat\mu_{0.1}\)</span>.
Comment on your findings.</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="resampling-methods.html#cb331-1"></a><span class="kw">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb331-2"><a href="resampling-methods.html#cb331-2"></a><span class="kw">boot</span>(Boston<span class="op">$</span>medv, <span class="cf">function</span>(v, i) <span class="kw">quantile</span>(v[i], <span class="fl">0.1</span>), <span class="dv">10000</span>)</span></code></pre></div>
<pre><code>## 
## ORDINARY NONPARAMETRIC BOOTSTRAP
## 
## 
## Call:
## boot(data = Boston$medv, statistic = function(v, i) quantile(v[i], 
##     0.1), R = 10000)
## 
## 
## Bootstrap Statistics :
##     original   bias    std. error
## t1*    12.75 0.013405    0.497298</code></pre>
<p>We get a standard error of ~0.5. This is higher than the standard error of the
median. Nevertheless the standard error is quite small, thus we can be fairly
confidence about the value of the 10th percentile.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="classification.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="linear-model-selection-and-regularization.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": {}
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/danhalligan/ISLRv2-solutions/edit/master/05-resampling-methods.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
